### ISSUE TITLE
FC-JIT order not having any SKU or Stomp Code

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1002]
OrderId: 165463SHE1068666, buyer: Vivaan Mishra, channel: FC-JIT, OrderStatus: Confirmed

![screenshot 2019-02-21 at 11 23 06 am](https://user-images.githubusercontent.com/39734400/53146693-311b0b80-35cb-11e9-8c38-4ec550d4ad92.png)

**Comment by crayonflakesmanu** [comment]
Pls update this order-

Order ID - 165463SHE1068666
AWB - 111191896673
Item sent - 00B6XT

**Comment by Krn7210** [comment]
Order Sync Issue Now It is resolved
