### ISSUE TITLE
User Reported Problem - Platform- Batch Generation-Pick sheet  |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1008]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Pick sheet need to be sorted by  Location id 
Router Link : /home

**Comment by Krn7210** [comment]
In paytm pick sheet it sorted by sku quantity before changing code it needs to be discussed
