### ISSUE TITLE
Un-mapped listing- SKU mapping 

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1009]
at channel list >azoi_in>unmapped listings :while trying to map Listingid with SKU, Search bar not able to Find SKU name  from data base.

E.g: while trying to map with listing id : 0117vq74n78 with Jan-1897 , No SKU name appear for mapping . 
![image](https://user-images.githubusercontent.com/47552051/53284413-033be100-3709-11e9-9daf-a6ce207e1333.png)

**Comment by mukeem1** [comment]
This has happen because in this UI I have tried to resolve sku by skuName but this listing was created by name, so  will handle this case in next build whereas this should work if listing is created using sku name.
