### ISSUE TITLE
User Reported Problem - Zephyrr-Replenish Report |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1016]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Replenish Report still getting 7595 SKU in list , after marking ageing this number should go down . Please check the reports
Router Link : /catalog/brands/3

**Comment by nishant1414** [comment]
You are getting these skus report because you are selecting all replenishmode,
if you want report for purticular replenishmode and then select that mode and click on submit.
you will not get report for all replenishmode.
