### ISSUE TITLE
Inventory missing during 2nd reconciliation

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#103]
Can you please validate the data for below boxes
1. BOX-15BX1 | 8-Jun | hari | 300
2. BOX-2BX2 | 6-Jun | hari | 37
3. BOX-2AX1 | 6-Jun | hari | 27
4. BOX-12BX1 | 9-Jun | hari | 20
5. BOX-15CX2 | 12-Jun | hari | 1088

1088/300 items missing from 1 box is huge. Can you check if they are moved or actually missing ?

**Comment by crayonflakesmanu** [comment]
Can someone check this out pls?

**Comment by nishant1414** [comment]
working on this
