### ISSUE TITLE
Product Image

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1037]
at any  report generation  below mention Image link is repeating on many SKU's 

[https://riptide.blob.core.windows.net/images/JAN-348_FrontDesign_Default_1.JPG](url)

Eg. Image for JAE-3293 is this
![image](https://user-images.githubusercontent.com/47552051/53633855-9d86b200-3c3e-11e9-81fa-98739fa7f9cf.png) 

however in any report section this image is visible
![image](https://user-images.githubusercontent.com/47552051/53633826-8c3da580-3c3e-11e9-85ec-faa13f6306f1.png)
moreover this  image is repeated in many sku's

![image](https://user-images.githubusercontent.com/47552051/53634038-23a2f880-3c3f-11e9-88ad-974e03dca942.png)

Please check 

--

**Comment by nishant1414** [comment]
we have solved image related issues
