### ISSUE TITLE
List of cancelled orders from FC

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#104]
Attaching the list of FC JIT cancelled orders. 
Pls remember to match the order id + sku before releasing the reserved items. Also if those items have come in scan lately. For rest of the items lets mark them missing, so that they can be made available if they come in scan next.

[DSOrderDetailReport (6).xlsx](https://github.com/StompMarket/helpdesk/files/2087594/DSOrderDetailReport.6.xlsx)

**Comment by nishant1414** [comment]
PlatformOrderId | paiddate | LastLocationModified | SellingAccountPrefix | orderstatus | ProductVariantCode | quantity | ItemNumber | status
-- | -- | -- | -- | -- | -- | -- | -- | --
3060356RWO828B339 | 6/7/2018 | 6/2/2018 | FC-JIT | 1 | G1-KD5/9-3_4 | 1 | 006F7R | 4
3060356RWO828B339 | 6/7/2018 | 6/2/2018 | FC-JIT | 1 | G1-KD1/35-3_4 | 1 | 006XW5 | 4
3520842RXN1483441 | 5/21/2018 | 5/12/2018 | FC-JIT | 1 | G17-KD93-3_4 | 1 | 005BGJ | 4
3557596RRO733C525 | 6/6/2018 | 6/5/2018 | FC-JIT | 1 | JP1-1/14-6_7 | 1 | 006VFH | 4
4210397RRO6024325 | 6/5/2018 | 4/28/2018 | FC-JIT | 1 | B1-T73-3_4 | 1 | 006OXU | 4
4327886RRO60A5974 | 6/5/2018 | 5/11/2018 | FC-JIT | 1 | G1-KWD1/10-18_24 | 1 | 005LS1 | 4
5263514RLO6A56939 | 6/5/2018 | 5/12/2018 | FC-JIT | 1 | G1-SKD3/31-6_7 | 1 | 006CLK | 4
551152RKO8297686 | 6/7/2018 | 4/28/2018 | FC-JIT | 1 | B1-T73-4_5 | 1 | 006OY1 | 4
5600690RMN1318111 | 5/21/2018 | 5/14/2018 | FC-JIT | 1 | G1-KD5/2-6_7 | 1 | 005MN1 | 4
5669374RPP03A0400 | 6/9/2018 | 5/30/2018 | FC-JIT | 1 | G1-SH31-7_8 | 1 | 0073LD | 4
5681219RAN6462536 | 5/26/2018 | 4/23/2018 | FC-JIT | 1 | B1-SH28-7_8 | 1 | 0069R6 | 4
  |   |   |   |   |   |   |   |  
  | cancelled orders and item did not come in scan after   being  reserved sold. |   |   |   |   |   |   |  
  | so these 11 items have been marked missing. |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
PlatformOrderId | paiddate | LastLocationModified | SellingAccountPrefix | orderstatus | ProductVariantCode | quantity | ItemNumber | status
2509002RQN7010038 | 5/27/2018 | 6/11/2018 | FC-JIT | 1 | G1-SKD1/4-6_7 | 1 | 006XU4 | 4
2509002RQN7010038 | 5/27/2018 | 6/11/2018 | FC-JIT | 1 | G1-SKD3/39-6_7 | 1 | 006L06 | 4
3557596RNO72AA168 | 6/6/2018 | 6/11/2018 | FC-JIT | 1 | G1-SKD3/44-6_7 | 1 | 006DOL | 4
5580860RLN7440172 | 5/27/2018 | 6/13/2018 | FC-JIT | 1 | G17-NS21-2_3 | 1 | 006W8R | 4
5631739RMO808A418 | 6/7/2018 | 6/11/2018 | FC-JIT | 1 | B1-T68-4_5 | 1 | 006OUT | 4

**Comment by nishant1414** [comment]
there were 57 cancelled orders in sheet
but i found 28 orders in database from them and marked cancelled.
and item details attached with those orders have been sent already

**Comment by crayonflakesmanu** [comment]
and what about these bottom 5 items ?
