### ISSUE TITLE
User Reported Problem - Salt Dispenser-2	Pending Acknowledgement  Cr-01	Pending Acknowledgement  Kaajal	Pending Acknowledgement  B-02	Pending Acknowledgement  |mohit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1043]
Partner : AESPL, User : mohit.whitecherry@gmail.com 
Problem : Salt Dispenser-2	Pending Acknowledgement 
Cr-01	Pending Acknowledgement 
Kaajal	Pending Acknowledgement 
B-02	Pending Acknowledgement 

Router Link : /fulfillment/fcs/217/packstations/batchorders/858

**Comment by Ronit1234** [comment]
we monitor on this bug
