### ISSUE TITLE
Reason for not populating the address when buyer is selected?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#105]
![screen shot 2018-06-11 at 10 28 15 am](https://user-images.githubusercontent.com/39734400/41213342-6c846090-6d62-11e8-9870-72b27e5ff3a0.png)

This address is entered separately.

**Comment by crayonflakesmanu** [comment]
Why is the address entered separately ? Moreover the + button is not visible in the default view. One need to resize the window to click it. Its been from quite some time now.

**Comment by k-abhinav** [comment]
handover to @akanksha-10

**Comment by mukeem1** [comment]
fixed
