### ISSUE TITLE
Why thumbnails at various report & catalog link don't show main image instead show zoomed or secondary shot

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1051]
![image](https://user-images.githubusercontent.com/39734400/53786950-3ff6ac00-3f43-11e9-8aab-9f388cb11d6d.png)

![image](https://user-images.githubusercontent.com/39734400/53786960-46852380-3f43-11e9-93e4-526491a21a03.png)

2 examples -

KSH-43
KSET-393

**Comment by DixitJoshi12** [comment]
done
