### ISSUE TITLE
Not able to specify multiple items for barcode generation

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1053]
If we need to reprint barcode of particular items - currently only 1 item can be printed at once leaving 1 barcode wasted. Can you please add option to specify multiple items to be taken out for barcode?

**Comment by anban4u** [comment]
Please check if this will be resolved once the find item screen is consolidated
Also @crayonflakesmanu  please check the barcode printing functionality at the available inventory tab on location under warehouses.

**Comment by crayonflakesmanu** [comment]
It's not working for us from that location.

![Screenshot 2019-03-09 16 02 31](https://user-images.githubusercontent.com/39734400/54070408-c41f9b00-4285-11e9-9db3-12daa9076ca2.png)

![Screenshot 2019-03-09 16 03 35](https://user-images.githubusercontent.com/39734400/54070413-cda90300-4285-11e9-9583-4068fc21e50c.png)

Or does it work some other way?

**Comment by akanksha-10** [comment]
This issue has been resolved and delivered in today's release.
