### ISSUE TITLE
Error Reported By  |team@jumkey.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1055]
Partner : jumkey, User : team@jumkey.com 
Problem : Error : The workbook must contain at least one worksheet 

 Message : https://stomp-api.azurewebsites.net/Catalog/brands/46/exportCatalog/download/excel?auth=eyJhbGciOiJIUzI1NiIsInR5cGJ50GNeETKKJ-DURk1i2OPgWQ&cachebuster=1551777361891 

 StatusText : Bad Request 

 User Comment : undefined 

Router Link : /catalog/brands/46

**Comment by DixitJoshi12** [comment]
no sku is created for the brand Oxidized so can't export brand catalog
