### ISSUE TITLE
User Reported Problem - Brands shown should just be authorized brands |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1056]
Partner : AESPL, User : anshul.bansal@gmail.com 
Problem : Please get it fixed immediately
Router Link : /inventory/fulfillmentcenter/AESPL_IN/location/6044/purchase/11322/items/new

**Comment by akanksha-10** [comment]
This has been fixed and released.
