### ISSUE TITLE
Batch generation 

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1063]
batch not generating for Flipkart and amazon Flex

**Comment by maheshstomp** [comment]
Today also no batch generated for both channel

**Comment by maheshstomp** [comment]
today only 1 order is recorded for FKOI in batch no.945 there are 8 orders .
![image](https://user-images.githubusercontent.com/47552051/54014221-f1931880-41a1-11e9-87be-ec24f6c4f7de.png)

also in amazon some orders still not in batch.

404-2647696-2141966
402-6509917-0910723
407-2188539-1259567
405-4644968-1101901
407-7765811-2682767
405-8814810-6689918
408-3167013-9845952
406-6747732-2609924
406-9042749-9025961

**Comment by Ronit1234** [comment]
Flex order not shown in any warehouse because fulfillmentCenter not assign on these orders
