### ISSUE TITLE
Inventory SYN

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1065]
Please check Inventory Sync for Flipkart Biosport panel .underneath data for all active listing .

JAN-1788
JAN-1273
JAN-1008
JAN-1157
JAN-1095
JAN-494
JAN-1294
JAN-1509
JAN-780
JAN-1840
JAN-1731
JAN-1592
JAE-609
JAE-461
JAE-3497
JAE-3283
JAE-518
JAE-2983
JAE-2720
JAE-1248
Jan-87
JAN-844
JAN-1454
JAN-759
JAN-1626
JAN-831
JAN-1581
JAN-937
JAN-1456
JAN-933
JAN-1453
JAN-517
JAN-1550
JAN-491
JAN-392
JAN-927
JAN-986
JAN-1103
JAN-1627
JAN-1552
JAN-794
JAN-1760
JAN-499
JAN-1519
JAN-989
JAN-1596
JAN-1810
JAN-1170
JAN-496
JAN-1504
JAN-786
JAN-1706
JAN-1187
JAN-1452
JAN-1750
JAN-389
JAN-926
JAN-1795
JAN-660
JAN-899
JAN-1239
JAN-1800
JAN-705
JAN-1458
Jan-29
JAN-882
JAN-1299
JAN-1030
JAN-1803
JAN-1171
JAN-827
JAN-1632
JAN-1486
JAN-758
JAN-1594
JAN-614
JAN-988
JAN-982
JAN-1565
JAN-1513
JAN-1416
JAN-1658
JAN-913
JAN-1011
JAN-1338
JAN-1761
JAN-1501
JAN-1764
JAN-753
JAN-784
JAN-1403
JAN-394
JAN-1362
JAN-313
JAN-1680
JAN-1582
JAN-985
JAN-818
JAN-1784
JAN-409
JAN-453
JAN-1797
JAN-1699
JAN-623
JAN-1624
JAN-1588
JAN-843
JAN-637
JAN-396
JAN-1508
JAN-1520
JAN-315
JAN-1098
JAN-1753
JAN-1752
JAN-1232
JAN-1477
HCBT-33
CO-1217
HCBT-20
JAN-1835
HCBT-65
HCBT-29
JAN-976
JAN-1726
JAN-1180
JAN-1510
JAN-890
JAN-1254
JAN-1175
JAN-791
JAN-1880
JAN-978
JAN-912
JAN-835
JAN-1131
JAN-1566
JAN-916
JAN-1342
JAN-1693
JAN-907
JAN-1720
JAN-282
JAN-769
JAN-609
JAN-1506
JAN-877
JAN-1010
JAN-1783
JAN-518
JAN-1292
JAN-1652
JAN-824
JAN-309
JAN-312
JAN-959
JAN-1324
JAN-1186
JAN-754
JAN-945
JAN-1794
JAN-1033
JAN-883
JAN-898
JAN-1661
JAN-1097
JAN-1700
JAN-1470
JAN-1571
JAN-1402
JAN-425
JAN-522
JAN-825
JAN-1511
JAN-1518
JAN-1237
JAN-377
JAN-1570
JAN-1284
JAN-1240
JAN-1480
JAN-621
JAN-1523
JAN-865
JAN-1524
JAN-1811
JAN-1455
JAN-339
JAN-1528
JAN-1182
JAN-1737
JAN-1586
JAN-983
JAN-922
JAN-995
JAN-1815
JAN-1796
JAN-1766
JAN-1564
JAN-1463
JAN-1123
JAN-1515
JAN-1691
JAN-1005
JAN-1812
JAN-904
JAN-1705
JAN-1763
JAN-1507
JAN-1792
JAN-1361
JAN-1879
JAN-797
JAN-1583
JAN-1191
JAN-816
JAN-1778
JAE-1813
JAE-1150
JAE-923
JAE-3251
JAE-3436
JAE-3351
JAE-459
JAE-3432
JAN-1833
JAE-1310
JAN-1310
JAN-342
JAN-853
JAN-1014
JAN-1525
JAN-1024
JAN-1102
JAN-610
JAN-947
JAN-1848
JAN-837
JAN-1012
Jan-84
JAE-929
JAN-266
JAN-847
JAN-994
HCBT-70
CO-1212
CO-1218
HCBT-36
HCBT-25
HCBT-15
JAN-766
JAN-1584
JAN-1479
JAN-1837
JAN-495
JAN-1567
JAN-542
JAN-1021
JAN-924
JAN-1615
JAN-1460
JAN-1545
JAN-513
JAN-624
JAN-631
JAN-1589
JAN-1772
JAN-944
Jan-77
JAN-1839
JAN-699
JAN-1802
JAN-383
JAN-560
JAN-1782
JAN-407
JAN-1630
JAN-751
JAN-1883
JAN-1781
JAN-1094
JAN-928
JAN-776
JAN-1471
JAN-905
JAN-1096
JAN-1543
JAN-1238
JAN-1762
JAN-1578
JAN-1468
JAN-1881
JAN-1505
JAN-1872
JAN-1466
JAN-839
JAN-1423
JAN-752
JAN-1574
JAN-1842
JAN-981
JAN-1809
JAN-1666
JAN-1183
JAN-1631
JAN-1106
JAN-903
JAN-939
JAN-1469
JAN-586
JAN-932
JAN-946
JAN-1790
JAN-771
JAN-1105
JAN-1659
JAN-1780
JAN-1013
JAN-1476
JAN-1768
JAN-1799
JAN-1686
JAN-840
JAN-1694
JAN-821
JAN-1770
JAN-1569
JAN-880
JAN-975
JAN-629
JAN-879
JAN-807
JAN-1563
JAN-424
JAN-1107
JAN-1399
JAN-488
JAN-593
JAN-1663
JAN-1804
JAN-900
JAN-1665
JAN-1016
JAN-1653
JAN-1275
JAN-863
JAN-672
JAN-1512
JAN-895
JAN-1655
JAN-1280
JAN-1773
JAN-1603
JAN-627
JAN-901
JAN-372
JAN-1703
JAN-1577
JAN-1660
JAN-1793
JAN-346
JAN-891
JAN-1657
JAN-456
JAE-1046
JAN-1172
JAN-990
JAN-690
JAE-3423
JAE-3015
JAE-1806
JAE-3027
JAE-2256
JAE-3332
JAE-3057
JAE-2197
JAE-1439
JAE-357
JAE-212
JAE-3231
JAE-460
JAE-3226
JAN-1882
JAN-414
JAE-836
CO-1220
HCBT-68
HCBT-7
HCBT-66
HCBT-31
HCBT-22
HCBT-61
HCBT-50
JAN-1656
JAN-426
JAN-1604
JAN-1268
JAN-917
JAN-1133
JAN-303
JAN-1767
JAN-1516
JAN-1813
JAN-960
JAN-920
JAN-902
JAN-1428
JAN-1093
JAN-1789
JAN-941
JAN-1687
JAN-823
JAN-842
JAN-915
JAN-1816
JAN-1635
JAN-1017
JAN-911
JAN-1878
JAN-1757
JAN-1210
JAN-896
JAN-1025
JAN-1269
JAN-1533
JAN-817
JAN-1711
JAN-893
JAN-812
JAN-854
JAN-380
JAN-597
JAN-1722
JAN-925
JAN-1785
JAN-355
JAN-1189
JAN-1572
JAN-866
JAN-1806
JAN-408
JAN-1502
JAN-1696
JAN-376
JAN-1344
JAN-302
JAN-592
JAN-1602
JAN-1628
JAN-772
JAN-993
JAN-974
JAN-1562
JAN-1735
JAN-1847
JAN-1598
JAN-878
JAN-1873
JAN-1573
JAN-1875
JAN-781
JAN-1637
JAN-1208
JAN-1605
JAN-1575
JAN-1104
JAN-1459
JAN-596
JAN-344
JAN-1390
JAN-1846
JAN-1109
JAN-1022
JAN-838
JAN-1421
JAN-1288
JAN-659
JAN-1807
JAN-940
JAN-1838
JAN-909
JAN-1432
JAN-1884
JAN-897
JAN-1551
JAN-636
JAN-1739
JAN-819
JAN-523
JAN-1110
JAN-1542
JAN-1354
JAN-846
JAN-1029
JAN-884
JAN-1535
JAN-1015
JAN-906
JAN-930
JAE-2337
JAE-1188
JAE-3031
JAE-2716
JAE-2268
JAE-1236
JAE-2339
JAE-1042
JAE-3205
JAE-3435
JAE-994
JAE-462
JAE-2307
JAN-1798
JAN-381
JAN-1270
JAN-1174
JAN-1031
JAN-1472
JAN-1467
JAN-1462
JAE-940
JAN-632
JAE-858
JAN-348
HCBT-57
HCBT-76
HCBT-35
JAN-1580
JAN-1579
JAN-881
JAN-1002
JAN-1473
JAN-1529
JAN-984
JAN-519
JAN-822
JAN-438
JAN-615
JAN-1591
JAN-1595
JAN-1814
JAN-1100
JAN-1309
JAN-1521
JAN-1527
JAN-1597
JAN-1765
JAN-626
JAN-1775
JAN-509
JAN-1517
JAN-612
JAN-808
JAN-1654
JAN-1343
JAN-1278
JAN-1874
JAN-943
JAN-390
JAN-1710
JAN-1758
JAN-1023
JAN-801
Jan-30
JAN-1485
JAN-1475
JAN-935
JAN-919
JAN-1633
JAN-1484
JAN-1801
JAN-1587
JAN-410
JAN-1701
JAN-894
JAN-934
JAN-549
JAN-1482
JAN-938
JAN-1003
JAN-1009
JAN-1876
JAN-1664
JAN-1744
JAN-1629
JAN-1759
JAN-1730
JAN-1401
JAN-1690
JAN-1478
JAN-1769
JAN-1877
Jan-79
JAN-1101
JAN-385
JAN-1734
JAN-284
JAN-1500
JAN-1474
JAN-961
JAN-958
JAN-645
JAN-1124
JAN-1779
JAN-1685
JAN-1857
JAN-1724
JAN-779
JAN-1433
JAN-1845
JAN-1684
JAN-793
JAN-1534
JAN-1411
JAN-1028
JAN-804
JAN-921
JAN-1276
JAN-1522
JAN-773
JAN-1590
JAN-908
JAN-1108
JAN-1625
JAN-1526
JAN-1843
JAN-1836
JAN-1503
JAN-1001
JAN-345
JAN-929
JAE-1378
JAN-1673
JAN-1481
JAN-1568
JAN-820
JAN-1593
JAN-1465
JAN-558
JAE-3250
JAE-2334
JAE-610
JAE-2338
JAN-102
JAE-2488
JAE-1796
JAE-1197
JAE-2898
JAE-820
JAN-942
JAN-613
JAN-872
JAN-261
JAE-432
JAN-357
JAN-1599
JAN-892
JAN-1026
JAN-308
JAN-633
JAN-1841
HCBT-21
CO-1213
HCBT-45
HCBT-3
HCBT-5
HCBT-73
HCBT-74
HCBT-39
HCBT-4
JAE-1399
CO-1211
JAN-457
JAN-471
JAE-1317
JAN-382
JAN-1199
JAN-1751
JAN-305
JAN-848
JAN-1259

**Comment by Ronit1234** [comment]
let me know all these variant sync with stomp inventory
