### ISSUE TITLE
Update Stages/Status of Zephyrr SKUs in Stomp

### ISSUE THREAD

**Issue by Arushi1Saxena** [StompMarket/helpdesk#1068]
https://docs.google.com/spreadsheets/d/1Pz2XlWC2Tmeys7X35ScZ7horojpYZBa5ghyIMeR5MsI/edit?usp=sharing

Update stages (Discard/Sampling/Replenishment) as mentioned against each SKU.

**Comment by DixitJoshi12** [comment]
done
