### ISSUE TITLE
User Reported Problem - Replenishment Issue CF/ Seet Kamal |singh.archna18@gmail.com 

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1069]
Partner : OIR, User : singh.archna18@gmail.com  
Problem : Inventory<Manage Purchase Order>http://app.stomp.market/inventory/purchaseorders/addskus/385897
Router Link : /inventory/purchaseorders/addskus/385335

**Comment by maheshstomp** [comment]
Not able to add purchase order >Inventory >manage purchase order > while trying to generate PO . In Sku find box cods for partners are not visible. 
![image](https://user-images.githubusercontent.com/47552051/54013971-0f13b280-41a1-11e9-8a5d-61a9c3974a9c.png)

**Comment by maheshstomp** [comment]
Also screen not scrolling(UP-Down or Side by Side ) after entering more then 6 SKU's. this make difficult to ensure item is added or not. 

![flipkart](https://user-images.githubusercontent.com/47552051/54020919-00cf9180-41b5-11e9-9fb4-e26e3ef8ead9.png)

**Comment by maheshstomp** [comment]
we have uploaded 15 sku's  in PO_OIR_4U6XTBZMPRX2, however only 3 Sku is saved .

Uploading screen.
![flipkart](https://user-images.githubusercontent.com/47552051/54021215-a2ef7980-41b5-11e9-86f4-b30a16313192.png)


Pending order screen 
![image](https://user-images.githubusercontent.com/47552051/54021247-b13d9580-41b5-11e9-9bf3-2ec94827d392.png)

**Comment by nishant1414** [comment]
all resolved
