### ISSUE TITLE
User Reported Problem - return issue  |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1071]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : qnbz ke return process nhi ho rhe hain 
Router Link : /inventory/fulfillmentcenter/5

**Comment by anban4u** [comment]
Can you check and figure out the exact issue here. Reassign to nishant when done.

**Comment by maheshstomp** [comment]
Order details are not generating for amazon flex orders .
![qnbz](https://user-images.githubusercontent.com/47552051/54509707-79321180-4970-11e9-9e5b-bdd5f72cc68a.png)


Mention tracking id also having the same issue.


710887430790
--
710888095325
710887838633
710888968230
710888580296
710889559055

**Comment by maheshstomp** [comment]
as orders are updated from FBA return are not processing
