### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1075]
Order which are shipped not getting removed from batch also the batch completely marked as shipped are still visible. There are 250 batch still available  

![image](https://user-images.githubusercontent.com/47552051/54103394-488f2c80-43f2-11e9-8714-003f3dbaadf7.png)

![image](https://user-images.githubusercontent.com/47552051/54103450-75434400-43f2-11e9-9af2-c15a00e1d372.png)

**Comment by Ronit1234** [comment]
Shipped Order from amazon not update with stomp
