### ISSUE TITLE
User Reported Problem - Sku Not Show if Stock Low or Zero |mohit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1088]
Partner : AESPL, User : mohit.whitecherry@gmail.com 
Problem : If Item Out of Stock or Zero , Sku Id Not Showing on Inventory Report
Router Link : /fulfillment/fcs

**Comment by anban4u** [comment]
Lets add an out of stock report
