### ISSUE TITLE
Catalog URL doesn't shows entire page if none of the items of have image

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#109]
See this example - 

http://catalog.stomp.market/catalog.html?keyword=Shirt&productType=KS&pageCount=1&isreplenishable=true&fc=cf_noida

None of the items on 1st page seem to have an image which causes the entire table to be hidden.

**Comment by crayonflakesmanu** [comment]
Catalog page issue.
Need size, our sku as well.

**Comment by nishant1414** [comment]
as I have checked and found that all the items on the first page have image.

**Comment by mukeem1** [comment]
done by nishant

**Comment by crayonflakesmanu** [comment]
What has changed here?
None of the catalog links are working.

http://catalog.stomp.market/catalog.html?keyword=Shirt&productType=KS&pageCount=1&isreplenishable=true&fc=cf_noida

http://stompcatalog.azurewebsites.net/catalog.html?keyword=Dress&productType=KD&pageCount=1&isreplenishable=true&fc=cf_noida
