### ISSUE TITLE
purchase screen testing errors

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1091]
1. we can duplicate SKU.
2. Sku count showing as 0 
![image](https://user-images.githubusercontent.com/47552051/54357929-26610d00-4685-11e9-8493-daf032c56d02.png)

3. Sku and quantity entered are still there after clicking the add sku button .
![image](https://user-images.githubusercontent.com/47552051/54358024-66c08b00-4685-11e9-88f4-1a5e3a4559a6.png)

4.Screen not scrolling after entering more then 6 sku's . up down or left right 
![image](https://user-images.githubusercontent.com/47552051/54358179-bacb6f80-4685-11e9-8f57-553330a8d468.png)

5. after clicking Draft button info label is blank  .
![image](https://user-images.githubusercontent.com/47552051/54358268-ecdcd180-4685-11e9-8041-041ef5feda47.png)

6. data is not getting back after drafting the PO.
7. data not getting back after saving the PO.
8. After saving PO , PO id still in pending tab not coming in confirm order tab.
9.  as tested po#384441 after receiving the po, data is not saved and Po is not available in line item tab .

**Comment by maheshstomp** [comment]
While receiving the PO if we accept the short quantity for SKU system generating rest SKU PLI @ 0   ..

E.g if PO was generated for 3 SKU's and we only received one SKU. PLi should generate for 1 sku however in current scenario system generating pli for all the SKU which was catered  in  PO

![image](https://user-images.githubusercontent.com/47552051/54531822-3b52de80-49ac-11e9-8022-e2f7533d0dfd.png)

**Comment by nishant1414** [comment]
1 - Now you cant add duplicate skus, if you add duplicate sku it will do sum of quantity.
2 - you can not add sku with zero quantity.
4 -  screen is scrolling after adding 6 rows.
5 - after clicking fab, snackbar is appeating with message 'Order has been save as draft'.
6 - we are getting data back after saving PO as draft.
7 - getting data back after saving PO as confirm.
8 - after saving PO, PO is appearing in confirm orders tab. 
9 - PO recieving is working fine now.
10 - If you are recieving short PO. it will work. if there are 3 skus exists in PO but you receive two skus with quantity. it will work .

**Comment by nishant1414** [comment]
images are also appearing.
