### ISSUE TITLE
User Reported Problem - D.O. Not Create |mohit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1092]
Partner : RBS, User : mohit.whitecherry@gmail.com 
Problem : We have not create D.O. on robust panel
Router Link : /inventory/fulfillmentcenter/215

**Comment by vermaanshul** [comment]
Robust ke Panel par DO create ho rahain hain...ye saturday ko check kiy thain
