### ISSUE TITLE
User Reported Problem - Sku id not showing on inventory report  |mohit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1095]
Partner : AESPL, User : mohit.whitecherry@gmail.com 
Problem : Sku id not showing on inventory report  if stock low or zero
Router Link : /inventory/fulfillmentcenter/217

**Comment by vermaanshul** [comment]
Iske liye sales report hain...ye bhee sumit aur mohit ko dhikayeen theen...iska workaround available hain
