### ISSUE TITLE
User Reported Problem - Hot Arrivals |mohit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1099]
Partner : AESPL, User : mohit.whitecherry@gmail.com 
Problem : Jab mein last 30 days ke hot arrival dekh rahain hoon to sku name, brand, listing date and image ...naheen aa raheen 
Router Link : /home

**Comment by DixitJoshi12** [comment]
ab aa rhe hai
