### ISSUE TITLE
User Reported Problem - TCW listing folder is not showing right listings |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#11]
Partner : OIR, User : anshul.bansal@gmail.com 
 Problem : I see a lot of listings which are sold or active in the folder. They should not be showing up there. Please resolve ASAP!
 Router Link : /channels/channels/12

**Comment by anban4u** [comment]
Ronit. Once you are done, please close this.

Since ronit is not yet on this helpdesk, assigning this to abhinav instead.

**Comment by Ronit1234** [comment]
Done
