### ISSUE TITLE
User Reported Problem - Return screen mein problem hein |mohit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1100]
Partner : AESPL, User : mohit.whitecherry@gmail.com 
Problem : Item ko receive kar rahein hain order ke against 7426823442...Paytm ke ASPL ka order hain...Returnitems screen par aayien...item condition select kee...to wo value enter karne ko bolta hain...kyan value enter karnee hain?...hamne 1 enter kar ke dekha par kuch huan naheen....iske bina return kaise hoga..please fix karon
Router Link : /inventory/fulfillmentcenter/217/returnitems/379821

**Comment by nishant1414** [comment]
you need to scan itemnumber there.

**Comment by vermaanshul** [comment]
Nishant...This is confusing...Mahesh told me that rack no to be provided....Decide what needs to be done here....and change the heading..Return process is not working because of this ...so please confirm
