### ISSUE TITLE
Sku Search Component

### ISSUE THREAD

**Issue by anban4u** [StompMarket/helpdesk#1102]
Add a core component for sku searching.
- [x] Add a core component
- [x] Take functionality from purchase line item screen or DO screen
- [x] sku autocomplete cell template - sku name, thumbnail, brand logo and variant code

**Comment by anban4u** [comment]
- [ ] Add a core component
- [ ] Take functionality from purchase line item screen or DO screen
- [ ] sku autocomplete cell template - sku name, thumbnail, brand logo and variant code

**Comment by pulkitr21** [comment]
Done
