### ISSUE TITLE
Batch not generated 

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1103]
Batch not generated for mention order id, from amazon .

408-7591617-6685158
--
405-3879113-8621963
403-1278488-8832324
402-2663709-8950706
406-3508433-9581159
408-6845286-7698745
406-9039942-4072313
405-2121840-3801142
406-4784851-9408302
406-2105629-8299554

**Comment by 044aman** [comment]
partially resolved but we fixed in next release
