### ISSUE TITLE
User Reported Problem - Channel > Reports> A.in Dashboard...No data coming  |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1115]
Partner : OIR, User : anshul.verma@sanskritii.com 
Problem : Channel > Reports> A.in Dashboard...No data coming 
Router Link : /channels/channellists/10/reports

**Comment by akanksha-10** [comment]
This issue has been fixed now and all reports are working properly under reports tab.
