### ISSUE TITLE
Enhancements to Transfer Screen

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#112]
1. Each transfer should display the total items in the transfer somewhere. No such info till now.
![screen shot 2018-06-12 at 12 31 54 pm](https://user-images.githubusercontent.com/39734400/41274911-c44093e6-6e3c-11e8-892b-9246e40c011f.png)

2. Transfer should have item level info. No such info as of now.
![screen shot 2018-06-12 at 12 32 11 pm](https://user-images.githubusercontent.com/39734400/41274990-0c482c1c-6e3d-11e8-825a-984107089357.png)

3. Definitely need option to remove items once added. No such scope now.

4. Pls add Alias (SKU) on this screen.
![screen shot 2018-06-12 at 12 32 11 pm](https://user-images.githubusercontent.com/39734400/41289814-996bec02-6e68-11e8-9465-29f4f0419a26.png)

**Comment by mukeem1** [comment]
#111

**Comment by anban4u** [comment]
Transfer now is just a package. This gets created only if there is a major movement of inventory from one warehouse to another.

Is this issue still valid?

**Comment by crayonflakesmanu** [comment]
Closing this.
