### ISSUE TITLE
getting duplicate packages  

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1128]
we are getting duplicate packages in some order screenshot attached .

![image](https://user-images.githubusercontent.com/47552051/54810277-b7e70500-4cab-11e9-8ab8-7e7ffe0b5bc3.png)

**Comment by maheshstomp** [comment]
![image](https://user-images.githubusercontent.com/47552051/54810365-f2e93880-4cab-11e9-8a6c-21a34822f499.png)

**Comment by nishant1414** [comment]
we have worked on this and have deleted duplicate packages.
Now only  package created against orders are visible.
