### ISSUE TITLE
Home page metric suggestions

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#114]
Would be helpful to have
1. Category wise total stock count.
2. Orders - if clicked, to have category wise bifurcation.
3. Items added to stock - to have no. of items moving to status 3 today. If clicked, can have more details from which all status to status 3. For example - 10 items from Missing to Available. 20 items from Waiting to be allocated to Available. etc.
4. Also just a total number of items at important status can be displayed. Like Available, Reserved, Missing

**Comment by nishant1414** [comment]
Ok we will give you these matrices by next week.
Once i will have to discuss these with Anshul Sir.
