### ISSUE TITLE
Why do we see same channel twice on this screen?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1143]
![Screenshot 2019-03-28 at 1 20 42 PM](https://user-images.githubusercontent.com/39734400/55139697-5c5dc100-515c-11e9-9e7b-be8aafb07e52.png)

Channel to see- FC-JIT 
Is it because of direct orders in that channel ?

**Comment by anban4u** [comment]
I think some DO that you have uploaded didn't have price mentioned. So the currency field is showing empty. Still lets have a check as there should be a currency selected by default always.
