### ISSUE TITLE
DO screen gives this every time, request does not completes any time

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#115]
![screen shot 2018-06-13 at 12 26 18 pm](https://user-images.githubusercontent.com/39734400/41335078-3aec3400-6f05-11e8-837c-a7ce7606286a.png)

**Comment by crayonflakesmanu** [comment]
Duplicate DO creation issue. Pls check

![screen shot 2018-06-23 at 1 15 52 pm](https://user-images.githubusercontent.com/39734400/41807144-a2e6d832-76e7-11e8-8ab1-a6a547473e70.png)

**Comment by mukeem1** [comment]
it is resolved in new version
