### ISSUE TITLE
Not able to create package for unpackaged orders

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1157]
FC-JIT
Order ID - 5326772SOH85FE621

![Screenshot 2019-03-30 at 12 12 46 PM](https://user-images.githubusercontent.com/39734400/55272646-98705d80-52e5-11e9-8273-0b41366edd82.png)

**Comment by nishant1414** [comment]
issue resolved, now you will be able to create package for unpackaged orders.
