### ISSUE TITLE
are orders not being marked shipped?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1158]
Last order marked shipped was from last year.

![Screenshot 2019-03-30 at 1 10 36 PM](https://user-images.githubusercontent.com/39734400/55273145-42071d00-52ed-11e9-9f99-3f95a2fe6ef9.png)

**Comment by nishant1414** [comment]
we have divided status in orderstatus and package status 
so here you are getting details of packages, and now shipped is a package status  and theses packages have been shipped and orders against theses packages have been fulfilled
