### ISSUE TITLE
Pending Issues to be closed today - Nishant

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1168]
Nishant, as discussed - here are the issues 

1. Feature to allow changing status of multiple items at once.
2. How to make packed items as available ?
3. Not able to ShipMark DO's #1050 
4. Are FC-JIT cancelled orders being synched with correct status from BT ?
5. Need option to print multiple barcodes at once (by item number) #1053 
6. FC-JIT B2B orders not reserving items (mapping missing) #300

**Comment by nishant1414** [comment]
1 - akanksha need to start working on this, hopefully will be delivered in next release.
2 - you can make packed items as available by scanning them  on a location in warehouse.
3 - Now we shipped package, once all the packages of an order are packed, order status will be fulfilled.
4 - there are 398 orders showing as cancelled in our status, I am sending you data, can you please ensure what is the exact status of these orders ?
5 - need to work on this.
6 - we need alias of those skus which are live on FC-JIT but not mapped on browntape.

**Comment by crayonflakesmanu** [comment]
Are these actually done?
1. Feature to allow changing status of multiple items at once.
2. Are FC-JIT cancelled orders being synched with correct status from BT ?
3. Need option to print multiple barcodes at once (by item number) #1053
4. FC-JIT B2B orders not reserving items (mapping missing) #300

**Comment by crayonflakesmanu** [comment]
@nishant1414
