### ISSUE TITLE
Error while opening a order 

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1169]
Created a blank DO under Wooplr channel.

![Screenshot 2019-04-04 at 4 53 18 PM](https://user-images.githubusercontent.com/39734400/55552163-428f2180-56fa-11e9-8da6-722df92813fd.png)

Order ID - 09AA00DL00000154 (first order in the above ss)
Error - Order ID missing 

![Screenshot 2019-04-04 at 4 53 25 PM](https://user-images.githubusercontent.com/39734400/55552168-4622a880-56fa-11e9-9bda-c80ec112a8d5.png)

**Comment by nishant1414** [comment]
data gap could not figure out what was it, 
now we have resolved this type of issuses, 
and do functionality working properly.
