### ISSUE TITLE
Direct order- Partial order getting updated 

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1193]
as per data base sku has been ordered in this DO , but in Stomp screen only three are visible
![image](https://user-images.githubusercontent.com/47552051/56131177-5f521180-5fa4-11e9-9488-9e5fe5e77cbc.png)

PlatformOrderId | OrderStatus | SkuName | OrderedQuantity | VariantCode | ProductVariantCode | Status | SellingAccountPrefix
-- | -- | -- | -- | -- | -- | -- | --
AB_US_1555067500235 | 3 | JAN-1854 | 1 | JAN-1854 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2723 | 4 | JAE-2723 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2723 | 4 | JAE-2723 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2723 | 4 | JAE-2723 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2723 | 4 | JAE-2723 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2784 | 2 | JAE-2784 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2784 | 2 | JAE-2784 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3401 | 4 | JAE-3401 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3401 | 4 | JAE-3401 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3401 | 4 | JAE-3401 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3401 | 4 | JAE-3401 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3400 | 4 | JAE-3400 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3400 | 4 | JAE-3400 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3400 | 4 | JAE-3400 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3400 | 4 | JAE-3400 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3464 | 2 | JAE-3464 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3464 | 2 | JAE-3464 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3621 | 5 | JAE-3621 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3621 | 5 | JAE-3621 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3621 | 5 | JAE-3621 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3621 | 5 | JAE-3621 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3621 | 5 | JAE-3621 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3626 | 3 | JAE-3626 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3626 | 3 | JAE-3626 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3626 | 3 | JAE-3626 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3629 | 3 | JAE-3629 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3629 | 3 | JAE-3629 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-3629 | 3 | JAE-3629 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-456 | 2 | JAN-456 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-456 | 2 | JAN-456 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-14 | 2 | Jan-14 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-14 | 2 | Jan-14 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-32 | 2 | Jan-32 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-32 | 2 | Jan-32 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-232 | 1 | JAN-232 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-414 | 3 | JAN-414 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-414 | 3 | JAN-414 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-414 | 3 | JAN-414 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-659 | 4 | JAN-659 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-659 | 4 | JAN-659 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-659 | 4 | JAN-659 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-659 | 4 | JAN-659 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-853 | 2 | JAN-853 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-853 | 2 | JAN-853 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-1747 | 1 | JAN-1747 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-1751 | 1 | JAN-1751 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-1870 | 1 | JAN-1870 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAN-1855 | 1 | JAN-1855 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2720 | 2 | JAE-2720 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2720 | 2 | JAE-2720 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2134 | 5 | JAE-2134 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2134 | 5 | JAE-2134 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2134 | 5 | JAE-2134 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2134 | 5 | JAE-2134 | NULL | NULL | AB_US
AB_US_1555067500235 | 3 | JAE-2134 | 5 | JAE-2134 | NULL | NULL | AB_US

**Comment by nishant1414** [comment]
As I have checked and found that 31 skus are visible in pack package screen, can you check again ?
