### ISSUE TITLE
User Reported Problem - No option to specify size in a new variant |manu@crayonflakes.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#12]
Partner : CF, User : manu@crayonflakes.com 
 Problem : Added KSH-222 (a new size) to a existing product.
Can't find a option to specify MRP, Size and also the save button is not available on trying to save these details the 2nd time.
 Router Link : /catalog/brands/5/products/202146/variants/217213

**Comment by crayonflakesmanu** [comment]
![screen shot 2018-05-29 at 6 30 24 pm](https://user-images.githubusercontent.com/39734400/40660548-ef4f7922-636e-11e8-92ab-89977b663f98.png)

**Comment by anban4u** [comment]
Neetu, lets discuss this.

**Comment by neetusingh1993** [comment]
Issue is resolved.Will be live on production by the end of the day
