### ISSUE TITLE
Order without packages screen not showing orders - IMP

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1202]
![Screenshot 2019-04-24 at 7 11 52 PM](https://user-images.githubusercontent.com/39734400/56663965-dda96480-66c4-11e9-8e16-527601f0d95c.png)

**Comment by anban4u** [comment]
@nishant1414  Please understand which orders are not showing up
@crayonflakesmanu we did add some filtering here as some FBA orders were showing up. FBA orders should not show up here as they are to be shipped from other party warehouses and hence no package is required. Can you let us know 1 or 2 orders which should have shown up here but do not?

Thanks!

**Comment by crayonflakesmanu** [comment]
Not able to find this 4225041SQK19F4777 (FC-JIT) anywhere. Probably item wasn't reserved hence should have gone under this screen.

**Comment by nishant1414** [comment]
now its working.
