### ISSUE TITLE
Why is status required with a item number ?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#121]
If one is searching a item by item number why is the status required ? I would guess - mostly the status would be unknown if some one is trying to find a item by it number.
![screen shot 2018-06-16 at 10 20 37 am](https://user-images.githubusercontent.com/39734400/41495882-329af5ba-714f-11e8-861e-a067d5bd4929.png)

**Comment by akanksha-10** [comment]
This issue has been resolved.
