### ISSUE TITLE
Cancelled Orders-Batch and Item status

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1211]
cancelled orders are not getting removed from batches and items also not getting released 
403-0951119-1097932
403-9117203-0841915

![image](https://user-images.githubusercontent.com/47552051/56796444-2cbfd880-6830-11e9-9454-8431b2509b7d.png)

![image](https://user-images.githubusercontent.com/47552051/56796835-06e70380-6831-11e9-8bd1-2b0a6303338b.png)

![image](https://user-images.githubusercontent.com/47552051/56796942-3f86dd00-6831-11e9-83fe-2bea09d63453.png)

**Comment by nishant1414** [comment]
as i have checked and found these orders are not related to any batch, means its working in a right way
