### ISSUE TITLE
Option to remove images is not working

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1216]
Giving error.

Till then pls remove the images for below styles at **product level**

G2-KD1-3
G2-KD1-8
G2-KD1-36
G2-KD1-39
G2-KD1-40
G2-KD1-56
G2-KD1-57
G2-KD1-58
G2-KD1-59
G2-KD1-60

G2-SKD1-6
G2-SKD1-7
G2-SKD1-8
G2-SKD1-10
G2-SKD1-11
G2-SKD1-13
G2-SKD1-14
G2-SKD1-15
G2-SKD1-31
G2-SKD1-34

**Comment by Krn7210** [comment]
done removed images
