### ISSUE TITLE
This data seems to be across sellers

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1241]
Great if it is intentional (means - since we do not have inventory view of OIR yet).

Example - Flipkart sale should be from Old India

![Screenshot 2019-05-04 at 4 59 17 PM](https://user-images.githubusercontent.com/39734400/57178471-1946ea00-6e8e-11e9-8cc2-495d09670671.png)

**Comment by nishant1414** [comment]
yes, this report is showing sale of your brands across all channels
