### ISSUE TITLE
Status 2 and on Shipping Container - Inventory Correction

### ISSUE THREAD

**Issue by vermaanshul** [StompMarket/helpdesk#1246]
When I run this query . I found 10035 items in 2019. This was a time when Shipping container was used to mark items out of Flex and FBAlite..

10000 seem to be a large data to me..so I segregated items based on month.....and cross-checked based on no of FBA orders on Az India flex orders and FA Lite orders...There is gap and probably it could be because of combos  but then I want you to check...

**Query**

select * from inventory.items i inner join 
inventory.ItemLocations il on i.LocationId = il.id
where il.FulfillmentCenterPrefix In ('ds_in', 'QNBZ','FA_OIR')
--and status =2 
and itemlocation like 'shipp%'
--and itemlocation like 'return%'
--group by itemlocation
--order by count(itemlocation)desc

**Month wise inventory connection**

![image](https://user-images.githubusercontent.com/25614944/57208268-968a7000-6ff0-11e9-9ea1-d51f3051233a.png)

**Comment by nishant1414** [comment]
need to work on data
