### ISSUE TITLE
Inventory Sync for Flipkart- Please validate

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1248]
Inventory count for more then 100 SKU are wrongly updated as mention in screenshot. We are selling items which we do not have inventory. (OD115396670731957000  )Today's Order
JAE-577
![image](https://user-images.githubusercontent.com/47552051/57209502-56c68700-6ff6-11e9-96b7-11140ef28e3c.png)
![image](https://user-images.githubusercontent.com/47552051/57209524-6b0a8400-6ff6-11e9-9ebe-81be327d3604.png)

JAN-805.

![image](https://user-images.githubusercontent.com/47552051/57209577-98efc880-6ff6-11e9-870c-0c32c999e083.png)

![image](https://user-images.githubusercontent.com/47552051/57209587-a2793080-6ff6-11e9-9353-162bc05cd2ac.png)

**Comment by maheshstomp** [comment]
OD115397571205060000

**Comment by Ronit1234** [comment]
done
