### ISSUE TITLE
PLI Created For 0 Item Received.

### ISSUE THREAD

**Issue by kalashashi** [StompMarket/helpdesk#1254]
![Purchase issue](https://user-images.githubusercontent.com/50194108/57354753-f5372180-7189-11e9-82be-6a9f4e4988a0.png)

Purhase Line Item Created For Item Which Were Not Received. Received (0) Quantity Of Some Items But Their PLI Created 45750,45751,45752,45753,45755.

**Comment by nishant1414** [comment]
now purchase line item is not creating for 0 quantity. bug fixed.
