### ISSUE TITLE
User Reported Problem - Add Column in Hot Arrivals- Stage (Replenish/GC/Sampling) |arushi2stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1257]
Partner : OIR, User : arushi2stompmarket@gmail.com 
Problem : Current Hot Arrivals report does not show the stage at which Variant is put, replenishment or discard.
Please add this column.
Router Link : /home

**Comment by nishant1414** [comment]
done
