### ISSUE TITLE
Download bug on the report screen

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1262]
Steps to replicate
1. Select any report and download its excel.
2. Change the report type to some other report without navigating to any other page.
3. Download this report type in the excel format.

This downloaded report is the 1st report which we downloaded.

In short - Downloading report is not changing the report type after 1st download.

**Comment by nishant1414** [comment]
as i have checked and found that there were some bugs in report downloading,
now all bugs have been resolved and its working fine.
