### ISSUE TITLE
User Reported Problem - item detail Not available at This screen |softtouchpisces@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1265]
Partner : AESPL, User : softtouchpisces@gmail.com 
Problem : Its a alibaba DO And We are Not Getting Any Detail about This

Router Link : /fulfillment/fcs/219/packstations/batchpackages/1165797/packpackage

**Comment by 044aman** [comment]
working fine.All data points are visible
