### ISSUE TITLE
Why is this sale not being reflected in partner sale

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1273]
Example SKU -> G2-SHORT47

![Screenshot 2019-05-22 at 4 51 37 PM](https://user-images.githubusercontent.com/39734400/58170770-00be3880-7cb2-11e9-8dac-7eba0063ecbc.png)

![Screenshot 2019-05-22 at 4 49 33 PM](https://user-images.githubusercontent.com/39734400/58170775-0451bf80-7cb2-11e9-91ee-c7a207ff9e62.png)

**Comment by nishant1414** [comment]
need to check.
