### ISSUE TITLE
We should show item number on this screen

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1280]
since there is only 1 item against a row - we should show the item number - would be very useful while processing.

![Screenshot 2019-05-28 at 8 50 55 AM](https://user-images.githubusercontent.com/39734400/58448489-c7f4e800-8125-11e9-866a-b2b6ac1668f1.png)

**Comment by nishant1414** [comment]
we cant show itemnumber on the same screen.
but we can add more tabs to show order and scanned items information of packages.

**Comment by nishant1414** [comment]
scanned items numbers tab is there, please check
