### ISSUE TITLE
What is the time zone on date? and how all is modified date affected?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1288]
![Screenshot 2019-05-29 at 8 34 24 AM](https://user-images.githubusercontent.com/39734400/58526441-9bf06a00-81ec-11e9-8e59-03d10ace7e3a.png)
What time zone is above modified date? UTC ?

How all is modified date affected ? Do you record user id modifying the order?

**Comment by anban4u** [comment]
This is utc. Lastmodified is the last modification made on the package at database level. This is more for internal consumption.
