### ISSUE TITLE
User Reported Problem - Report did not Not Work Correctly  |softtouchpisces@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1290]
Partner : INGM1, User : softtouchpisces@gmail.com 
Problem : If We Are Downloading Next Report then We get Both In Excel
Router Link : /inventory/fulfillmentcenter/220

**Comment by nishant1414** [comment]
need to check download as csv

**Comment by akanksha-10** [comment]
Resolved already
