### ISSUE TITLE
User Reported Problem - Please add location  |softtouchpisces@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1291]
Partner : INGM1, User : softtouchpisces@gmail.com 
Problem : Sometimes rack name and location would be different So seller wants location In this View And download 
Router Link : /inventory/fulfillmentcenter/220

**Comment by akanksha-10** [comment]
I have added rack location column on locations tab and resolved bug of basic info location field. It will be delivered in the next release.
