### ISSUE TITLE
FC JIT order - Not able to scan item in SM

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#131]
Order ID : 2228526RXQ25B0447

Shipping the below item. SM not accepting due to mapping issue.
Item : 00728G

Pls resolve.

**Comment by anban4u** [comment]
Nishant, please check and verify

**Comment by nishant1414** [comment]
As I have checked there is no mapping issue.
If you have any further issue with this item, please provide screenshot to us.
