### ISSUE TITLE
Error Reported By  |anmol.kanawade@ingrammicro.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1332]
Partner : INGM1, User : anmol.kanawade@ingrammicro.com 
Problem : Error : No prepared package is available to manifest 

 Message : https://stomp-api.azurewebsites.net/package/fcs/ING-BWND1/manifests?auth=eyJhbGciOiJIUzI1NiIsInR5cEDx4FOhy_8b2xjYqxLueGerc4&cachebuster=1560853524732 

 StatusText : Bad Request 

 User Comment : undefined 

Router Link : /fulfillment/fcs/220/packstations

**Comment by 044aman** [comment]
resolved
