### ISSUE TITLE
Error Reported By  |sachinaheda@ingrammicro.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1354]
Partner : INGM1, User : sachinaheda@ingrammicro.com 
Problem : Error : Http failure response for https://stomp-api.azurewebsites.net/package/fcs/ING-BWND1/manifests?auth=eyJhbGciOiJIUzI1NiIsInR5c__0t1I-oVTZJctquVJ9-Y-vuM&cachebuster=1562308074616: 400 Bad Request 

 Message : undefined 

 StatusText : undefined 

 User Comment : undefined 

Router Link : /fulfillment/fcs/220/packstations

**Comment by 044aman** [comment]
resolved
