### ISSUE TITLE
Wrong Quantity Showing on Gl_RD listing page 

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#1356]
On Listing page
![image](https://user-images.githubusercontent.com/47552051/60868040-bc7afd80-a249-11e9-873f-9efd6baf9783.png)

On inventory page 
![image](https://user-images.githubusercontent.com/47552051/60868054-c8ff5600-a249-11e9-9e33-c9d9859e66c5.png)

**Comment by Krn7210** [comment]
fixed
