### ISSUE TITLE
Updating SKU name from the UI, doesn't reflects in the barcode file downloaded

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#136]
For example, we have fixed the SKU number for the attached styles, but when taking out the barcode it gives wrong (old) SKU.

![screen shot 2018-06-23 at 4 26 04 pm](https://user-images.githubusercontent.com/39734400/41808879-33cbf930-7702-11e8-9bc9-42af56d4a737.png)

**Comment by anban4u** [comment]
Abhinav, you need to check and let me know.

**Comment by k-abhinav** [comment]
handover to @mukeem1

**Comment by mukeem1** [comment]
Variant Name(Alias) can not be updated. Not Allowed. Changing field to read Only
