### ISSUE TITLE
User Reported Problem - No Order details showing when we are find order in manifested |softtouchpisces@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1381]
Partner : STMPD, User : softtouchpisces@gmail.com 
Problem : No Order details showing when we are find order in manifested
Router Link : /fulfillment/fcs/234/packstations/batchpackages/679218/orderdetail/packageId/1274927

**Comment by Krn7210** [comment]
As Checked Its Showing
