### ISSUE TITLE
Find Item directly on clicking a button from reserve sold screen would be super useful - Enhancement

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#139]

**Comment by anban4u** [comment]
Not sure which screen is this. @crayonflakesmanu can you provide the url of the screen. You can simply browse to the screen and copy the address from the browser address bar.

Thanks!

**Comment by crayonflakesmanu** [comment]
http://app.stomp.market/inventory/reports
![screen shot 2018-06-29 at 10 46 50 am](https://user-images.githubusercontent.com/39734400/42074479-228b1eb2-7b8a-11e8-8827-dde0f2c1e057.png)

**Comment by crayonflakesmanu** [comment]
Is this feasible? Currently tough to find items after checking in the reserved report.
Fo ex - After checking reserved item of a variant which is not available on the rack - we need to trace item history for which one has to copy item number and go to the find item screen.

![screen shot 2018-07-11 at 3 36 00 pm](https://user-images.githubusercontent.com/39734400/42565170-5c1f2476-8520-11e8-82ca-5fa3f58f1307.png)

**Comment by crayonflakesmanu** [comment]
any update?
