### ISSUE TITLE
User Reported Problem -   Requirment |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#140]
Partner : OIR, User : shashikala251@gmail.com 
Problem : (1)Change item status
(a)Checked out for samples (b) scarpped (c)Reservescarp 
(2)manage transfer 
(3)get variant images 

Router Link : /home

**Comment by mukeem1** [comment]
Required 2 and 3 are already available 
1. Requirement 1 for item status change. new screen or some other way will be given soon.
