### ISSUE TITLE
User Reported Problem - Usability issues |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1425]
Partner : STOMP, User : anshul.bansal@gmail.com 
Problem : 1. FC Prefix hint text should read unique warehouse code
2. FC Prefix box should be first one
3. Self Managed Warehouse vs Stomp Managed Warehouse should be a slider below fc prefix field

Router Link : /inventory/fulfillmentcenter/new

**Comment by akanksha-10** [comment]
Resolved and delivered already.
