### ISSUE TITLE
Error Reported By  |prashant.dalvi@ingrammicro.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1436]
Partner : INGM1, User : prashant.dalvi@ingrammicro.com 
Problem : Error : Http failure response for https://stomp-api.azurewebsites.net/Metrics/itemsLifecycleReport/partnerPrefix/INGM1?auth=eyJhbGciOiJIUzI1NiIsInR5coe0uoaxYtm8qV5bdv95dcoSPs&cachebuster=1565072020017: 400 Bad Request 

 Message : undefined 

 StatusText : undefined 

 User Comment : unable to download this report  

Router Link : /inventory/itemslifetime

**Comment by akanksha-10** [comment]
This is working fine.
