### ISSUE TITLE
Error Reported By  |anshulverma@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1444]
Partner : OIR, User : anshulverma@gmail.com 
Problem : Error : Http failure response for https://stomp-api.azurewebsites.net/Catalog/brands/106/channels?auth=eyJhbGciOiJIUzI1NiIsInR5cK60Zg4EAjRIrOMat7eI8Si2iA&cachebuster=1565517176486: 400 Bad Request 

 Message : undefined 

 StatusText : undefined 

 User Comment : undefined 

Router Link : /catalog/brands/106

**Comment by DixitJoshi12** [comment]
There is no channel connected with Brand Test(106)
