### ISSUE TITLE
Error Reported By  |anshul.verma@search-value.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1448]
Partner : OIR, User : anshul.verma@search-value.com 
Problem : Error : Http failure response for https://stomp-api.azurewebsites.net/metrics/statusWiseCount/OIR?auth=eyJhbGciOiJIUzI1NiIsInR5cfeTVeY0rm-EmUmuePAaFRbtfI&cachebuster=1565529184953: 404 Not Found 

 Message : undefined 

 StatusText : undefined 

 User Comment : undefined 

Router Link : /home

**Comment by DixitJoshi12** [comment]
This issue has been resolved and data will be available in next release
