### ISSUE TITLE
User Reported Problem - SellingAccountPrefix -AB_US have 4 package in packed status but we can't generate manifest  |softtouchpisces@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1452]
Partner : OIR, User : softtouchpisces@gmail.com 
Problem : We found some kind of error please check and resolve 
Router Link : /fulfillment/fcs/5/DS_IN/channels/AB_US/packagesummary/1

**Comment by akanksha-10** [comment]
No longer valid.
