### ISSUE TITLE
Error Reported By  |anmol.kanawade@ingrammicro.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1477]
Partner : INGM1, User : anmol.kanawade@ingrammicro.com 
Problem : Error : Http failure response for https://stomp-api-testing.azurewebsites.net/Inventory/updateItemQualityStatus/item/02S3OE/qualityStatus/passed/reason/undefined?auth=eyJhbGciOiJIUzI1NiIsInR5c05ZeD2cy1hCb3Ny7RwSqp8UIM&cachebuster=1566881910801: 400 Bad Request 

 Message : undefined 

 StatusText : undefined 

 User Comment : undefined 

Router Link : /inventory/fulfillmentcenter/220

**Comment by akanksha-10** [comment]
no longer valid
