### ISSUE TITLE
Error Reported By  |sachinaheda@ingrammicro.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1484]
Partner : INGM1, User : sachinaheda@ingrammicro.com 
Problem : Error : Http failure response for https://stomp-api.azurewebsites.net/api/Fulfillment/batches/5784/pickitem/02LZD0?auth=eyJhbGciOiJIUzI1NiIsInR5cybmaxcs_2bolv0qgCjLuk-ALY&cachebuster=1567227765587: 400 Bad Request 

 Message : undefined 

 StatusText : undefined 

 User Comment : undefined 

Router Link : /fulfillment/fcs/220/packstations/batchpackages/5784

**Comment by akanksha-10** [comment]
no longer valid.
