### ISSUE TITLE
User Reported Problem - Location Reconciliation screen |manu@crayonflakes.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#15]
Partner : CF, User : manu@crayonflakes.com 
Problem : If the filter is removed - it doesn't gives back the entire result. Even after resubmitting the form or going to some other tab.
Router Link : /inventory/fulfillmentcenter/13/locations/2531

**Comment by anban4u** [comment]
Neetu. You need to check this.

**Comment by mukeem1** [comment]
Reconciliation screen working.
