### ISSUE TITLE
Error Reported By  |maheshmadkar@ingrammicro.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#1520]
Partner : INGM1, User : maheshmadkar@ingrammicro.com 
Problem : Error : Http failure response for https://stomp-api.azurewebsites.net/Inventory/fcs/ING-BWND1/locations/11845/items/02P2WS02P2WU?auth=eyJhbGciOiJIUzI1NiIsInR5cNY-07gzhe9ZPMwngnyt2fO2E8&cachebuster=1568887970342: 400 Bad Request 

 Message : undefined 

 StatusText : undefined 

 User Comment : undefined 

Router Link : /inventory/fulfillmentcenter/220/locations/11845

**Comment by akanksha-10** [comment]
This issue is no longer valid.
