### ISSUE TITLE
Issues in creating new variant

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#154]
1. After creating a new variant in an existing product, adding title does not enables the save button.
2. No MRP field in the new variant creation or editing screen.

Example - KD-1975

**Comment by anban4u** [comment]
Nishant please check on 1.

For 2, we need to add a pricing tab to variant and product. This needs to be part of the release v0.8

**Comment by nishant1414** [comment]
Now its enable please check

**Comment by nishant1414** [comment]
now
