### ISSUE TITLE
Need copy image URL option in the images tab of a variant

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#155]

**Comment by anban4u** [comment]
Assigning to nishant. My assumption is this issue should solve once we provide upload images by product. This functionality exists on the new 0.8v app. Nishant to verify with manu and close this.

**Comment by crayonflakesmanu** [comment]
any update?

**Comment by crayonflakesmanu** [comment]
Can't see this functionality yet. Any plans?

**Comment by nishant1414** [comment]
done

**Comment by crayonflakesmanu** [comment]
I don't see this feature?
Can you confirm if it is released? or pl share a screenshot on where to find it.

**Comment by mukeem1** [comment]
![image](https://user-images.githubusercontent.com/18714966/45861444-29400c80-bd8a-11e8-938f-7f4aea83806b.png)

**Comment by mukeem1** [comment]
there is a button just above the upload fab.
