### ISSUE TITLE
Image visible on variant detail page but not on the product detail page

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#161]
Image visible on variant detail page but not on the product detail page. Making it tough for us to identify which products are missing on images.

![image](https://user-images.githubusercontent.com/39734400/42121318-7300dfce-7c4a-11e8-9f23-c1cfde9d9382.png)
![image](https://user-images.githubusercontent.com/39734400/42121319-76f18be2-7c4a-11e8-84e6-bec51db6c998.png)

**Comment by mukeem1** [comment]
resolved
