### ISSUE TITLE
Item not available on the rack even after reconciliation

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#169]
we have been receiving orders for items which are not present in the inventory even after following the reco process.

Item no - 006DJX
It should have been present in BOX-9EX1 from 25/4. This box was reconciled on 12/5, last scan date on the item search page says - 12/5 but no event in the detail page.
Can you check its events and help us understand what could be the issue?

**Comment by Krn7210** [comment]
As we have checked and found that it was reserve sold on 2-7-18 
and we cannot found any event on 12/5 because sometimes event fail
