### ISSUE TITLE
User Reported Problem - Combo Issue |singh.archna18@gmail.com 

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#170]
Partner : OIR, User : singh.archna18@gmail.com  
Problem : Co-1089 have two buttons (button-182, button-193) in this combo but when we check, only button 193 image is appearing.

Router Link : /catalog/brands/3/assembledskus/201780

**Comment by nishant1414** [comment]
Co-1089 have two buttons (button-182, button-179) in this combo and image is appearing of both skus.
please check again. solved.
