### ISSUE TITLE
Amazon is reserving items from our warehouse

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#173]
Looks like amazon orders are reserving our warehouse inventory and when we give a particular item via transfer to OIR, why the items are not being released ??

ItemNumber | Name | Ordereddate | OrderId | SAP | Image

007Q9S | G16-WNS3-11_12 | 02/07/18 | 407-4685000-8387505 | AzOI-IN | 
007Q1M | B16-WNS8-7_8 | 02/07/18 | 407-1487287-2939543 | AzOI-IN | 
0054FT | B1-SH12-3_4 | 24/06/18 | 406-3379133-1885163 | AzOI-IN |

**Comment by k-abhinav** [comment]
This happens because of CF_NOIDA connected to AzOI-IN, But now this is disconnected.
