### ISSUE TITLE
Why are there still so many reserved items ?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#174]
486 unintentional total reserved items.

HS-SOR
134 items against 140017
3 items against 133198
2 items against each 138475 & 138927
5 items against HS 8 (April)
1 item against NS Giral 1. Many items available in this order - why?

FC-JIT
164 items against FC JIT order since April.

Rest against no-order.

**Comment by k-abhinav** [comment]
As per our discussion, we are releasing a feature for heal ReserveSold items to Available. So hope this issue will not occur further!!

For the above data, @nishant1414  will check out once.

**Comment by Krn7210** [comment]
as per discussion i have mailed all items to nishant
