### ISSUE TITLE
Not able to book a DO from the new beta version

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#176]
[DO issue on beta version.zip](https://github.com/StompMarket/helpdesk/files/2163437/DO.issue.on.beta.version.zip)
![screen shot 2018-07-04 at 6 21 44 pm](https://user-images.githubusercontent.com/39734400/42280890-a44112d4-7fbf-11e8-8509-ba869e8edbcf.png)

Attached the csv file and scanned items that we have sent.

**Comment by k-abhinav** [comment]
bug found and resolved in stomp-beta!!
