### ISSUE TITLE
User Reported Problem - Can't drill down into line item click for purchase |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#20]
Partner : OIR, User : anshul.bansal@gmail.com 
Problem : Selected purchase 6744. And clicked on a line item. Nothing happened.
Router Link : /inventory/purchases/6744

**Comment by neetusingh1993** [comment]
Done..Will be available on production by evening

**Comment by neetusingh1993** [comment]
Done
