### ISSUE TITLE
Not able to upload images on Beta version neither at product level nor at variant level.

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#201]
![screen shot 2018-07-05 at 7 20 18 pm](https://user-images.githubusercontent.com/39734400/42327070-80da4832-8088-11e8-98e0-3a53e58bf4d4.png)

![screen shot 2018-07-05 at 7 20 49 pm](https://user-images.githubusercontent.com/39734400/42327106-976c8b50-8088-11e8-909c-24c49d06bf8c.png)

**Comment by mukeem1** [comment]
fixed.
