### ISSUE TITLE
User Reported Problem - Requirment Download Option |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#202]
Partner : OIR, User : shashikala251@gmail.com 
Problem : Purchase,Warehouse,Find Items
Router Link : /inventory/purchases/new

**Comment by k-abhinav** [comment]
Trying to understand the problem, help me out @mukeem1 @nishant1414

**Comment by mukeem1** [comment]
it is working
