### ISSUE TITLE
Frequent timeout issue on beta

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#204]
![screen shot 2018-07-06 at 5 02 42 pm](https://user-images.githubusercontent.com/39734400/42376932-a97b9f0a-813e-11e8-8756-687c7ed76338.png)

**Comment by k-abhinav** [comment]
This is temporary issue, now resolved. If you are having the same problem again, you can reopen the issue.

**Comment by crayonflakesmanu** [comment]
Session is not retained long enough like earlier version.

![screen shot 2018-07-11 at 10 00 24 am](https://user-images.githubusercontent.com/39734400/42550805-78cb0fb0-84f1-11e8-8478-179f411e96c1.png)

**Comment by crayonflakesmanu** [comment]
No option for me to reopen this issue.

**Comment by crayonflakesmanu** [comment]
Can someone pls reopen this issue? Have to sign-in roughly after every hour of inactivity.
