### ISSUE TITLE
User Reported Problem - Merge barcode screen with this.  |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#21]
Partner : OIR, User : anshul.bansal@gmail.com 
Problem : 1. Need to add more search options to this screen.
2. Should be able to select items from the list. Including select all
3. Should be able to generate barcodes based on selected items.
Router Link : /inventory/finditems

**Comment by mukeem1** [comment]
done
