### ISSUE TITLE
Not able to update our SKU name from the catalog option

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#244]
Trying to update SKU for the below variant
OLD SKU Name - B17-SH16--3_4
New SKU Name - B17-SH16-3_4

Before - 
![screen shot 2018-07-14 at 1 03 22 pm](https://user-images.githubusercontent.com/39734400/42722251-6aab9bd0-8766-11e8-96ea-2c1e8b2fddfe.png)

![screen shot 2018-07-14 at 1 03 30 pm](https://user-images.githubusercontent.com/39734400/42722263-9413950e-8766-11e8-8e52-fad1a2de5959.png)

After (full reload / logout) - 
![screen shot 2018-07-14 at 1 03 37 pm](https://user-images.githubusercontent.com/39734400/42722268-9e8d89fe-8766-11e8-81ea-79390f2c2f51.png)

**Comment by mukeem1** [comment]
name updation of sku is not allowed. client side UI bug
