### ISSUE TITLE
User Reported Problem - Main image swap issue on KDP78 |manu@crayonflakes.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#25]
Partner : CF, User : manu@crayonflakes.com 
Problem : Close up image seems to be the main image per the variant list view, however the front image is uploaded for the variant.
Router Link : /catalog/brands/5/products/191826

**Comment by crayonflakesmanu** [comment]
![screen shot 2018-06-01 at 7 24 51 am](https://user-images.githubusercontent.com/39734400/40816905-1243127c-656d-11e8-8402-f7cdd6e6b20b.png)

**Comment by anban4u** [comment]
We need to add a functionality on Catalog screen that allows users to upload images on products and let them duplicated across variants.

**Comment by neetusingh1993** [comment]
@crayonflakesmanu  don't worry about the ordering of images..image showing in the list is for view purpose only.

**Comment by neetusingh1993** [comment]
This will show up in release 0.7
