### ISSUE TITLE
Items available but can't find their location, last scanned also not available, how?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#250]
![screen shot 2018-07-16 at 12 42 55 pm](https://user-images.githubusercontent.com/39734400/42746544-e4f5265a-88f5-11e8-92f6-4bdf0717f5a5.png)

Item not available on the rack.

**Comment by k-abhinav** [comment]
Don't now how it is possible, meanwhile status set as WaitingToBeAllocation.
[AvailableButLocationIsNullItems.xlsx](https://github.com/StompMarket/helpdesk/files/2204477/AvailableButLocationIsNullItems.xlsx)
