### ISSUE TITLE
User Reported Problem - Replace Fulfillment Center with Warehouse |arushi2stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#26]
Partner : OIR, User : arushi2stompmarket@gmail.com 
Problem : Replace all 'fulfillment center' or 'FC' terms with warehouse for documentation.
Router Link : /fulfillment/processShipment

**Comment by anban4u** [comment]
Please change all terminology for FC. Use Warehouse wherever Fulfillment center is used in the stomp app.

**Comment by mukeem1** [comment]
Almost all are replaced. There may be remaining some terminology. IF you found somewhere. please let me know i will update those too. @anban4u
