### ISSUE TITLE
After creating A Direct Shipment, Fields don't go blank allowing us to create a next one.

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#271]
![screen shot 2018-07-18 at 11 58 40 am](https://user-images.githubusercontent.com/39734400/42863826-090e173a-8a82-11e8-9bce-f888900008a6.png)

**Comment by crayonflakesmanu** [comment]
Not able to add 2nd item to this direct shipment.

**Comment by crayonflakesmanu** [comment]
any updatE?

**Comment by akanksha-10** [comment]
This issue has been resolved.
