### ISSUE TITLE
Need an option to export generic feed file

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#276]
Having the below fields atleast

SKU
Product Type
Title
Description
color
size
Image 1
Image 2
Image 3
Image 4

**Comment by crayonflakesmanu** [comment]
any update?

**Comment by crayonflakesmanu** [comment]
any plans on this?

**Comment by mukeem1** [comment]
cli tool developed. we will intergrate it in dashboard

**Comment by mukeem1** [comment]
done
