### ISSUE TITLE
How and when was this item allocated to a location?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#287]
![screen shot 2018-07-26 at 6 13 00 pm](https://user-images.githubusercontent.com/39734400/43262987-95b2d508-90ff-11e8-9691-1ac96b413e3f.png)

![screen shot 2018-07-26 at 6 13 06 pm](https://user-images.githubusercontent.com/39734400/43262988-978a0a5e-90ff-11e8-9a19-949626501937.png)

**Comment by mukeem1** [comment]
Some events seems missing for the item. Eventing system has been improved. Hope you will not find such issues in future.
