### ISSUE TITLE
FC-JIT B2B order picking wrong SKU, hence not allowing to scan items - IMP

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#300]
![screenshot 10](https://user-images.githubusercontent.com/39734400/43397106-5481c9ac-9421-11e8-8611-71f36d5e74e2.png)

Order ID's of these orders end with "D"

**Comment by crayonflakesmanu** [comment]
Did anyone had a chance to look into this one?

**Comment by crayonflakesmanu** [comment]
Pls update if anyone plans to look into this?
Its important for us.

**Comment by crayonflakesmanu** [comment]
Another critical issue for us -
![screen shot 2018-08-25 at 11 10 11 am](https://user-images.githubusercontent.com/39734400/44615416-7a2a1700-a857-11e8-9eca-0e5b5cc0e19a.png)

**Comment by mukeem1** [comment]
What  i found out is that this is happening in case of unmapped skus

**Comment by crayonflakesmanu** [comment]
I think your analysis is not complete.
See below example-
Order ID: 181618V92A9F0D
FCID: 2231650
SKU: B1-SH69-2_3 (present on stomp)
Stomp Code: KS-537

Still it is being shown on Stomp as below:
![screen shot 2018-08-31 at 3 33 02 pm](https://user-images.githubusercontent.com/39734400/44906646-22961a80-ad33-11e8-85ad-db8eb9ca01d8.png)

Pls acknowledge.

**Comment by mukeem1** [comment]
Sku is created on stomp but it is not mapped on browntape. 
![image](https://user-images.githubusercontent.com/18714966/44909398-c932e900-ad3c-11e8-8e1b-09536954776c.png)

**Comment by mukeem1** [comment]
MAPPING OF 967 SKUS IS DONE. SOME DUPLICATE ARE LEFT.
Working on skus resolution of  skus of b2b orders. As BT giving productId in those cases.

**Comment by mukeem1** [comment]
no update from browntape.

**Comment by crayonflakesmanu** [comment]
any update from BT?
been more than 2 months since this issue was opened.

**Comment by mukeem1** [comment]
No, I talked with BT team today's morning. They are saying that they haven't resolved the issue yet. 
BT's team will update on monday for detailed analysis of issue.

**Comment by mukeem1** [comment]
No update from BT

**Comment by crayonflakesmanu** [comment]
Pls follow up with BT on this else escalate this at right place.

**Comment by crayonflakesmanu** [comment]
This issue was resolved earlier but seems has reappeared now.
Example Order ID - 191919S559D96D

It is fetching FCID in place of SKU hence not reserving items and giving warning while packing order. Request you to please resolve this.

**Comment by crayonflakesmanu** [comment]
another example from mail-

![screenshot 2019-03-05 at 12 41 08 pm](https://user-images.githubusercontent.com/39734400/53787191-ff4b6280-3f43-11e9-8515-91e46d52df0d.png)

![screenshot 2019-01-14 at 12 01 29 pm](https://user-images.githubusercontent.com/39734400/53787259-4c2f3900-3f44-11e9-811d-18095371f521.png)

**Comment by crayonflakesmanu** [comment]
Whats the update on this ? 
Inventory is being messed up because of these B2B orders. I guess mapping needs to be fixed.
