### ISSUE TITLE
Why enter on this screen doesn't work ?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#302]
![screen shot 2018-07-31 at 6 04 18 pm](https://user-images.githubusercontent.com/39734400/43459776-32a5c1e6-94ec-11e8-9b7a-76da4d538217.png)

**Comment by anban4u** [comment]
Just wrap the controls in a form. That should be able to trigger the search on enter keypress

**Comment by crayonflakesmanu** [comment]
When is it planned?

**Comment by akanksha-10** [comment]
This has been added. It will be displayed in the next release.
