### ISSUE TITLE
Why can't I attach this item to a new order ?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#303]
This item seems to be a return. Stomp not allowing to change status or attach this to a new FC order.
![screen shot 2018-07-31 at 6 05 52 pm](https://user-images.githubusercontent.com/39734400/43459846-7906a48e-94ec-11e8-8f32-1db895df7479.png)

As per Jitender - Packed item status can't be changed ever - they are entering this data in the google doc.

Pls dont' change the status of the item from the backend.

**Comment by anban4u** [comment]
System should give a specific error dialog telling user
"This item has already been packed to order <order id>. Are you sure you want to repack this into order <New order id>". The dialog box should have "Yes" and "No" buttons. On yes, it should swap. On no, it should ignore.

**Comment by mukeem1** [comment]
re-designing this functionality.

**Comment by mukeem1** [comment]
change item status provided and re-designing of shipment is pending
