### ISSUE TITLE
Why do I see so many brands here? I am not selling them 

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#304]
![screen shot 2018-08-01 at 11 59 55 am](https://user-images.githubusercontent.com/39734400/43504848-77b01b4c-9582-11e8-9002-151998b312bd.png)

**Comment by anban4u** [comment]
Two reasons
1. The call to get brands is not contextualized or
2. The user has a catalogadmin role. These roles should not be provided to anyone.

**Comment by mukeem1** [comment]
User was having catalogAdmin role. Now I have removed the role.
