### ISSUE TITLE
Not able to use Change Item status screen on the new panel.

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#310]
![screen shot 2018-08-09 at 10 52 10 am](https://user-images.githubusercontent.com/39734400/43879553-4a70e5a8-9bc2-11e8-80e1-89293ef59d8a.png)

, doesn't works here. But why a comma is needed between 2 item number - if it is scanned, it would take an enter. Was this functionality tested?

![screen shot 2018-08-09 at 10 53 12 am](https://user-images.githubusercontent.com/39734400/43879590-6fc9db66-9bc2-11e8-8e71-4fde3f85b4d6.png)

How is it implied that a search button is needed to take an action on already searched item. It should be something like a edit functionality. I couldn't understand for few days - how to change the status.

On top of all, how can we change status of multiple items at a time - changing status 1 by 1 is not feasible for us. Since you have taken down the old portal - request you to please fix this asap.

**Comment by anban4u** [comment]
This is another usability issue with change status screen. We should be able to support multiple items scan using a text area instead of a text box.
