### ISSUE TITLE
Properties text box present twice on new sku page, which one to enter

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#315]
Title, size etc are present twice on this new sku page. Which field to enter data ?

![screen shot 2018-08-07 at 10 09 49 am](https://user-images.githubusercontent.com/39734400/43754802-460ffca4-9a2a-11e8-8d3d-41b9c5d847a2.png)

![screen shot 2018-08-07 at 10 08 21 am](https://user-images.githubusercontent.com/39734400/43754807-4dffccbe-9a2a-11e8-8510-91b3b5c58ecc.png)

**Comment by mukeem1** [comment]
data problem. will clean up this

**Comment by mukeem1** [comment]
fixed.
