### ISSUE TITLE
Orders taking somewhere between 30 to 60 mins to reflect.

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#320]
Order at 8:56 not reflected till 9:34

![screen shot 2018-08-08 at 9 34 03 am](https://user-images.githubusercontent.com/39734400/43815650-5a780abe-9aee-11e8-9b43-2b63dbb3e90f.png)

![screen shot 2018-08-08 at 9 36 24 am](https://user-images.githubusercontent.com/39734400/43816435-6a454098-9af2-11e8-8fe5-1c83f62a9161.png)

**Comment by anban4u** [comment]
Mukeem to investigate how long it is taking for BT orders to sync. Maybe Karan can pitch in too.

**Comment by crayonflakesmanu** [comment]
Orders haven't synched after 3pm yesterday. Can you pls look into this?
And also setup a email trigger for such scenarios.

**Comment by mukeem1** [comment]
Order sync is updated to run it after every 10 mins. Hope issue is resolved now.
