### ISSUE TITLE
Question regarding direct shipment / order id consistency

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#321]
What will happen I we create a Direct Shipment with a order id under a channel which syncs the same order via BT later for the same channel.

Our scenario - 
If I create a FC-JIT order (for times when orders are not reflected) via a direct order and it sync later as well.

**Comment by anban4u** [comment]
The order coming from BT should be updated in that case. Mukeem needs to investigate if that is what is happening and report back.

**Comment by mukeem1** [comment]
same order modifies. If order is created using direct shipment and later it sync via BT sync or from other sync, same order will be modified and it will not created duplicate shipped item. It works as it is expected to work.
