### ISSUE TITLE
Pending Shipments

### ISSUE THREAD

**Issue by anban4u** [StompMarket/helpdesk#329]
1. When clicked on pending shipment button (left nav bar), all shipments pending for last 1 week should be displayed
2. User should be able to find the order based on order id or sku or item number or any other scheme that is required.
3. Solve all the bugs on the scan screen.
4. Ship the item - provide awb, shipper. Allow user to set values as default
5. Automatically print - invoice and address label ( on same sheet), and if brand label is required - then print on zebra (if it is connected)
6. Mark the item as shipped on platform

**Comment by mukeem1** [comment]
#412 will have reference to this issue too.
