### ISSUE TITLE
Direct Shipment screen doesn't works most of the time.

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#336]
![screen shot 2018-08-11 at 6 00 21 pm](https://user-images.githubusercontent.com/39734400/43991711-7def9026-9d90-11e8-89a9-3d4a80bce14c.png)
![screen shot 2018-08-09 at 6 14 18 pm](https://user-images.githubusercontent.com/39734400/43991712-83cbc212-9d90-11e8-8381-9a08e82ab21b.png)

Attached 1 item - screen says 2

![screen shot 2018-08-09 at 6 11 22 pm](https://user-images.githubusercontent.com/39734400/43991717-928cc314-9d90-11e8-97eb-0a2229e67494.png)

**Comment by anban4u** [comment]
Mukeem to solve this one.

**Comment by crayonflakesmanu** [comment]
is this resolved?

**Comment by crayonflakesmanu** [comment]
Still facing this.

![screen shot 2018-08-20 at 10 31 56 am](https://user-images.githubusercontent.com/39734400/44321227-5be1a700-a464-11e8-867b-e5544e41e9f2.png)

No option for me to *reopen.
