### ISSUE TITLE
Report page not showing any options even after few mins

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#347]
![screen shot 2018-08-13 at 5 41 54 pm](https://user-images.githubusercontent.com/39734400/44031012-396e8a60-9f20-11e8-8141-77deb6c4db69.png)

**Comment by nishant1414** [comment]
As I have checked and found that reports are working.
can you tell me which one report you were looking for ?

**Comment by crayonflakesmanu** [comment]
Entire system was not working at that time hence closing this issue.
