### ISSUE TITLE
Pls name the downloaded report file name with some logic

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#348]
Example of a downloaded file -> "ReportType_Date"

**Comment by nishant1414** [comment]
ok, it should be done by today.

**Comment by crayonflakesmanu** [comment]
Is this released ? Cant see this yet.

**Comment by nishant1414** [comment]
now it will release on friday.

**Comment by nishant1414** [comment]
done, you will get this today.

**Comment by crayonflakesmanu** [comment]
All name start with report and then the date. Why not give it reporttype_date
Example - ReservedItems_30082018, LocationCount_30082018, StatusCount_30082018
Otherwise all the downloaded reports look the same and you have to open each of the downloaded reports to look out for the exact one.
Let me know if it makes sense.

**Comment by crayonflakesmanu** [comment]
Do you agree with the above request ?
All the items and report on same day has same name.

![screen shot 2018-09-17 at 1 07 12 pm](https://user-images.githubusercontent.com/39734400/45610734-9eee6480-ba7a-11e8-8fb5-ae3a31e42d06.png)
