### ISSUE TITLE
Listing Coverage - Please investigate

### ISSUE THREAD

**Issue by AnshulVermaStomp** [StompMarket/helpdesk#363]
Please discuss this with Mahesh and investigate why coverage for old items is not complete. After analysis please come back why these items are not coming in feed files....If these are coming in feed file then why not listed so far...

I have compared the listing data on multiple platforms..

https://docs.google.com/spreadsheets/d/1msIeCjJS39BxwaA6A0emWGFTUvhw3nBrj-GOnXAks8k/edit#gid=0

**Comment by mukeem1** [comment]
need more discussion with **Mahesh**  about pending listings and strategies around it.

**Comment by mukeem1** [comment]
for listing CLI tool is provided.
