### ISSUE TITLE
User Reported Problem - AZKK-us Order |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#367]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : JAE-1745 Item number not generated 
Router Link : /fulfillment/exportSheet

**Comment by Krn7210** [comment]
![screenshot-1](https://user-images.githubusercontent.com/31442799/44394823-c6bedb00-a555-11e8-8ffd-ac4829969ebd.png)


It is visible in 19/08/2018 picksheet.
