### ISSUE TITLE
These SKUs are not coming in Feedfile for SNS - KK -.com - Neither in Feed file not in error file

### ISSUE THREAD

**Issue by AnshulVermaStomp** [StompMarket/helpdesk#379]
SL-1856
--
WSL-406
SR-340
SL-1857
DRS-296
DRS-299
DRS-294
DRS-298
DRS-332
DRS-289
DRS-302
DRS-301
DRS-305
DRS-297
DRS-300
DRS-325
DRS-322
DRS-308
DRS-256
DRS-303
DRS-304
DRS-291
DRS-307
NDC-314
SL-1858
SL-1860
SL-1859
NTP-447
NTP-448
NTP-440
NTP-450
NTP-442
NTP-449

**Comment by Krn7210** [comment]
currently these variant are inactive
