### ISSUE TITLE
User Reported Problem - Flipkart merchent shipmark screen pe Order id show nhi oh raha hi |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#381]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : OD113089465366478000
Router Link : /fulfillment/processShipment

**Comment by nishant1414** [comment]
this order id exists in flipkart.orderitems but not in fulfillment.shipmentorders.
