### ISSUE TITLE
User Reported Problem - Return BOM & BLR items Change FC , DS_virtual... |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#383]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 0046M2
0046M0
0046M3
0046MF
0046M6
0046LK
0046M4
0046LO
0046LJ
0046LX
0046LN
0046lr
0046M1
0046ME
0046MD
0046M7
0046LY
0046LQ
0046MC
0046MG
0046lu
0046MG
0046LV
0046LP
0046LZ
002JVF
002JVI
002JVG
002JVK
002jvj
002JVH
000XCO
000HAE
003M87
000WHD
000WGW
000WGV
000WGS
000WGP
000WGL
000WGM
000WGK
000WGJ
000WGG
000WGC
000WGI
000WGF
001CFC
001CFD
001CF6
001CF0
000WHO
000WGZ
000WHE
001CF9
001CF8
000WHG
000wht
001CTL
001CTN
001CG2
001CFX
001CSV
001CT9
001CT0
001CG1
001CFW
001CG5
001CGC
001CG7
00cgh
001CFV
001CT4
000tii
000TJ3
001CSL
001CGF
001CT5
001CTC
003JOC
003job
0031HW
00459Z
00477Z
00477I
00477N
00478K
00477Y
00477C
00477H
004773
00478H
00478F
00476P
00476Z
00476N
00476O
004766
00478B
004787
00475V
00475R
004762
00478A
00475U
0047J1
00472W
0047IU
00472Y
00473A
00473R
004756
00474C
00475I
004748
00474W
00473F
004770
0047L6
0047LA
0047L7
0047JP
0047K3
0047KP
0047K6
0047L1
0047IM
0047JV
0047KY
0047IG
00479M
0047AL
00479F
0047a1
00479N
00478Y
00478V
00478N
00478s
0047HY
0047BN
0047A4
0047B7
0047B2
0047bs
0047B9
0047bd
0047c5
0047CH
0047BY
0047CA
0047IF
0047CE
0047cc
0047HW
0047FH
0047F6
0047CI
0047DR
0047CM
0047DH
0047DM
0047dd
0047DE
0047D7
0047DB
0047D0
0047CS
0047HM
0047CL
0047FP
0047GX
0047GZ
0047H9
0047GP
0047FX
0047GO
0047GB
001VRR
0047DS
0047E1
0047E8
0047EM
0047EQ
0047EZ
0047EK
0047FJ
0047EN
0047E5
002JVF
003WZO
002ZJM
00460E
00460F
00460J
004621
00460H
00460N
00465L
00467R
00467C
00466V
004672
00465M
00467D
0045YD
0045YE
0045YO
00460B
0045YT
0045YZ
0045YW
0045YR
0045YH
0045Z7
0045ZE
0045ZK
0045ZD
0045ZJ
0045ZN
0045ZU
0045YG
0045Z4
0045YM
0045ZV
004602
0045ZP
0045ZW
004609
0045ZX
0045Z8
0045ZB
0045ZI
0045ZG
0045Z9
0045YF
0045Z6
00460A
004605
0045ZC
0010GN
006HN0
00460E
0049X2
004L5V
003M0N
002U2Q
0049UJ
004AJJ
002WIG
003YD2
0049RK
002CVL
0049XZ
002U5R
0045TS
0046L7
004AIU
002WGA
002U2C
003XL0
0049U1
00460H
002U1S
003960
0017CV
004DYX
004AIJ
004AGY
002TXT
004AJX
0049WF
0049T3
002WCM
0049WQ
002IMU
001HE5
003WTJ
003AN0
002J1G
003IHU
324X20318
001ZM5
001ZM1
0010RN
0045GV
0045GX
0045GW

Router Link : /home

**Comment by Krn7210** [comment]
done
