### ISSUE TITLE
User Reported Problem - required barcode for cloudtail  |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#393]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : required bar codes for cloudtail for all PO 
2HSB1SSE
5Z4DXVOZ
66CL9NOL
6XXJU89C
6ZSBGC4R

7HUCWGYZ

Router Link : /home

**Comment by mukeem1** [comment]
provided
