### ISSUE TITLE
User Reported Problem - CR uploading not completed.... |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#402]
Partner : BS, User : shashikala251@gmail.com 
Problem : Error!
Http failure response for https://stomp-api.azurewebsites.net/Catalog/requirements/26/skus?auth=eyJhbGciOiJIUzI1NiIsInR5ckgtXn8BX-qjHcg63Nj1QprW90&cachebuster=1535174689861: 400 Bad Request

{"$id":"1605271","error":["The instance of entity type 'ProductType' cannot be tracked because another instance with the key value '{Id: 207}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached."]}

Router Link : /catalog/catalogrequirements/26

**Comment by mukeem1** [comment]
Catalog CR hasn't been fixed in new flow.
