### ISSUE TITLE
User Reported Problem - Pick list  |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#406]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Pick list for amazon.uk is populating incorrect data there 11 orders  but pick up sheet given only 3 .Please check 
Router Link : /inventory/finditems

**Comment by mukeem1** [comment]
All were created. Some of them are from amazon.fr and amazon.de channel which are connected to selling account AzOI-UK.
