### ISSUE TITLE
Why are the transferred products in reserved state at our warehouse?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#409]
007Q23 | G16-WNS2-6_7 | 01/08/18 | 406-7341977-9310766 | AzOI-IN | https://riptide.blob.core.windows.net/thumbnails/KNS-78_Frontandbackmerge_DEFAULT_1.JPG | TransferId:3291
-- | -- | -- | -- | -- | -- | --
007Q5M | G16-WNS4-2_3 | 31/07/18 | 171-3161632-5674756 | AzOI-IN | https://riptide.blob.core.windows.net/thumbnails/KNS-82_ARTISTIC1_DEFAULT_1.JPG | TransferId:3280

**Comment by nishant1414** [comment]
platformorderid | paiddate | SellingAccountPrefix | ProductVariantCode | ItemNumber | transferid | Sourcefc | DestinationFc | transferdate
-- | -- | -- | -- | -- | -- | -- | -- | --
171-3161632-5674756 | 7/31/2018 | AzOI-IN | KNS-82 | 007Q5M | 3280 | CF_NOIDA | DS_IN | 8/1/2018
406-7341977-9310766 | 8/1/2018 | AzOI-IN | KNS-78 | 007Q23 | 3291 | CF_NOIDA | DS_IN | 8/3/2018
