### ISSUE TITLE
User Reported Problem - Returns Items FC Change DS_VIRTUAL..... |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#418]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 004TCH
0065IU
005DUL
004TCP
875X78
745X46
0014II
652X16
002RET
0013ZG
001LK5
836X55
000UP3
764X18
113X9004
0020M8
004tbu
003xs7
0048sd
004hbx
0052qo
004hnz
004mfg
002way
003chu
003m3s
0040zn
006s2a
8700x1
8346x14
0040yw
00650p
7910x25
0064fp
001x67
002v5c
00423j
002peb
001t8t
8570x2
0065mh
002mcu
7997x3
00274c
004e5l
001maw
001o1t
004h6g
002ep1
000wd5
0056jj
8700x4
000l9i
00274d
004mnw
004el9
004moq
004fia
00299x
8346x2
004mqo
0034np
005qzl
00664y
003iqv
0013zl
394x25604
860x11
7903x1
003iqu
004fkq
291x17157
667x118
827x70
7905X21
005244
170X10017
004YIO
002V3O
0003BS
0014KF
001B0B
000VWN
000UI8
008AV8
006S3O
0064GC
001NEZ
002HGV
001S0D
002XUZ
007NGD
004DZ8
004MRI
001O4Q
001FWK
006R9F
002EQB
003PAK
006RXZ
001C9X
001CAG
001CAI
001CAD
001C9Y
001CAW
001C9T
0043CC
005NB5
001402
918X116
918X156

Router Link : /home

**Comment by Krn7210** [comment]
done
