### ISSUE TITLE
User Reported Problem - FC change DS_VIRTUAL... |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#420]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 440X80
717X183
645X38
0020ME
645X17
000KEM
920X265
000SQW
8881X23
22X1015
00264P
000XYW
002J4O
001NLY
008I6Z
002J4P
004TGN
000N0N
00263K
004PAT
0022DU
0022DV
0022DR
0022DQ
0023EN
000LA9
0047WB
0047WF
0047WO
0047WQ
0047W7
0047W2
004FS5
0051GV
000UVC
004CPO
001FWX
001FW1
0006GL
0023EO

Router Link : /inventory/finditems

**Comment by Krn7210** [comment]
done
