### ISSUE TITLE
Selecting a date range on the orders list gives inconsistent results

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#431]
Default view on orders tab with out selecting date range

![screen shot 2018-08-30 at 5 47 15 pm](https://user-images.githubusercontent.com/39734400/44851114-e7391480-ac7c-11e8-8ecb-f1a7a6b3957f.png)

After selecting date range - 25/8/18 to 30/8/18(current date)
![screen shot 2018-08-30 at 5 49 22 pm](https://user-images.githubusercontent.com/39734400/44851167-10f23b80-ac7d-11e8-8685-d9e275a4a623.png)

Today's orders are lost. 

Also, on adding created date & modified date column - We see all these orders are created at the same time. How come?
I think date column should be present as the first column and by default.
![screen shot 2018-08-30 at 5 50 51 pm](https://user-images.githubusercontent.com/39734400/44851281-69293d80-ac7d-11e8-9c4f-806617194172.png)

**Comment by mukeem1** [comment]
this is because of datetime conversion as selected datetime takes one day lesser than the actual selected

**Comment by crayonflakesmanu** [comment]
This should be handled then - maybe add one day while fetching results..
Also, having date as 1st column would be helpful.
