### ISSUE TITLE
User Reported Problem - Flipkart Replenishment  |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#44]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Flipkart replacement  
Router Link : /home

**Comment by k-abhinav** [comment]
This will be available after this release.

**Comment by anban4u** [comment]
What is required in this one. Need to follow up with Mahesh and Anshul Verma to figure out the exact requirement.

**Comment by nishant1414** [comment]
as per discussed with mahesh ji no further required
