### ISSUE TITLE
User Reported Problem - FC change DS_VIRTUAL ...... |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#446]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 0017SG
001DMW
000R3I
0040ZP
002EPB
000H01
004E4V
002WAH
003GDA
003GCK
003TD5
000Z7L
001IGV
8481x88
0010L3
8319X9
8255X7
00014X
00014V
000B7H
8843X1
694X55
812X22
8481X73
904X28
001D66
8036X13
851X6
812X16
8376X16
8040X19
004JH6
0015I9
002JXL
0048SN
001QIZ
002HC1
004DZC
00508Y
00299S
001QJU
003OYD
001QJU
0022DY
7844X1
0022E0
002HFM
0064RI
002ZM0
002NA6
003FJE
000IHB
003XK4
004EO8
003LZX
003LZU
004ML4
002EPB
8481X13
8481X12
8815X9  
Router Link : /inventory/barcodes

**Comment by Krn7210** [comment]
done
