### ISSUE TITLE
User Reported Problem - amazon |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#455]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : order sync not working for any amazon platform 
Router Link : /catalog/brands/9/assembledskus

**Comment by anban4u** [comment]
@Ronit1234  Is this not working?

**Comment by Ronit1234** [comment]
working perfectly no issue
