### ISSUE TITLE
User Reported Problem - FC change DS_VIRTUAL..... |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#456]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 0046mp
0046mn
0046mj
0046mo
0046mk
0046mm
0046ml
0047i3
0047fo
00478l
00478m
0047ct
0047h3
0047i2
0047et
0047fn
0047f5
0047he
0047e0
0047fg
0047fr
000h5g
004mps
004xed
004o29
004p3n
004kcy
004msj
0048x9
00474m
001ug5
004nzq
00504y
004nlx
003lyu
004ml7
004n6p
004xd5
004n6g
004mrn
004ms0
004r8e
004vx0
004n7p
002xv1

Router Link : /inventory/fulfillmentcenter/204

**Comment by akanksha-10** [comment]
done
