### ISSUE TITLE
Is Reconciliation making old items missing/available?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#460]
BOX-16EX2 was reconciled on 28-Aug as per our records. However items are still reserved from 11-June order in it. Can you please check? Assuming items are being marked missing/available if reserved earlier than 5 days for all our channels.

11/06/18 | 140017 | HS-SOR

**Comment by crayonflakesmanu** [comment]
any decision on this ?

Making old reserved items (>5 days) missing if not found in reconciliation ?

**Comment by nishant1414** [comment]
No, we are not making old reserved items missing/available if not found in reconciliation.
