### ISSUE TITLE
User Reported Problem - Return items FC change DS_VIRTUAL . |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#468]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 008fzm
0014ke
8684x38
008pa3
007727
001v2p
008lx4
002jlm
008pb6
003mss
008p33
00001q
008xl0
894x19
000kq0
113x9000
004tyf
0041wn
000y2c
008wut
005hly
003r11
002qqq
008azz
006c18
008cu5
008cwb
0017rp
0079x3
008cui
0079x2
004p4i
004oix
003psg
00504w
004jyj
004p6v
004jw9
004mtb
001t8n
004w9j
000hae
004wb0
007JQ6
004hyi
0046ot
004qq9
004mnj
003ps0
004z26
004p7j
003ucj
004xd3
004qrm
004qpl
004sz6
004mr5
004qup
001ql5
004kfk
004oj2
0045tw
004p40
004n7e
004xd4
00505b
004mqm
004z0o
004sza
003ucy
004s8f
003puj
004xd6
004veq
0048t0
004mqw
0048vu
003kly
003pq6
004o22
004mob
00505e
004mlj
0046xt
004mlq
003klv
004mlf
0045p7
0046fh
004ml8
004z5q
004mo3
004p47
004mts
004szp
004p6t
004qu8
0045sk
004ml2
0050gl
004n7m
004mq0
004n6x
003pum
004s6m
004szk
004n93
004p6y
003oft
004mnc
004mtt
0045sq
004nlp
004xdb
004mo7
004p75
004mi5
004t4m
004fqz
004qru
0046or
004mo2
004mtm
004s7z
004nl8
004n8y
004mlu
004w9s
004p7m
004o1e
004oph
003kkx
Router Link : /inventory/finditems

**Comment by akanksha-10** [comment]
done
