### ISSUE TITLE
User Reported Problem - Allow user to add vendor.  |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#47]
Partner : OIR, User : anshul.bansal@gmail.com 
Problem : Vendors need to be added to a partner's vendor list. Vendors are going to be partners - added by other partners. Lets add a screen for that.
Router Link : /inventory/purchases/new

**Comment by akanksha-10** [comment]
Only server API call is pending

**Comment by anban4u** [comment]
This has been done.
