### ISSUE TITLE
Inconsistent data across screens, which data to trust

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#471]
![screen shot 2018-09-10 at 3 52 39 pm](https://user-images.githubusercontent.com/39734400/45292076-b45f0e00-b511-11e8-833f-ec822fe02208.png)

![screen shot 2018-09-10 at 3 52 25 pm](https://user-images.githubusercontent.com/39734400/45292077-b4f7a480-b511-11e8-9a8a-c6cd70594809.png)

**Comment by nishant1414** [comment]
ordered quantity with this order is 537
reserved items  13
packed items 510
and shippeditems 4
in direct orders we are showing only reserved and packed items not shipped items.
but when you search order in channel list you have total count of item numbers attached with this order.
thats why it is showing 527 items in below report.

**Comment by crayonflakesmanu** [comment]
I think you need to represent it better. Also why only 1 items in shipped ?
In channel list - packed & shipped should be different then.
