### ISSUE TITLE
Stomp not allowing partial FC-JIT order to be shipped

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#472]
Issue in cases of accessories+apparel order

**Comment by mukeem1** [comment]
partial order shipmark is not allowed in  system but will add this this functionality very soon.

**Comment by crayonflakesmanu** [comment]
I think it was allowed earlier.

**Comment by mukeem1** [comment]
checked out code, i found that it wasn't rolled out. we will do it in this week

**Comment by mukeem1** [comment]
done. will be rolled out in this milestone.
