### ISSUE TITLE
User Reported Problem - stomp Issue |akashk02001@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#483]
Partner : OIR, User : akashk02001@gmail.com 
Problem : stomp se barcode nhi nikle rhe hai ve error de rha hai
Router Link : /fulfillment/processShipment

**Comment by mukeem1** [comment]
done

**Comment by mukeem1** [comment]
multiple listings of same sellersku with different case ex JAE-144  and jae-144
