### ISSUE TITLE
Difference in the Available count

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#493]
[Archive.zip](https://github.com/StompMarket/helpdesk/files/2381936/Archive.zip)

Count of total Available items from export of location gives 24410
and available items from status report gives 24444.

Can you check why is this difference (incase 34 units are not reserved within time difference of downloads) ?

**Comment by akanksha-10** [comment]
This has been resolved but still there is a gap of 1 item that I am not able to find.
