### ISSUE TITLE
Images not visible on catalog after upload

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#501]
![image 5](https://user-images.githubusercontent.com/39734400/45547653-22bc0d00-b83f-11e8-88f0-671800f9e62a.png)
![image 6](https://user-images.githubusercontent.com/39734400/45547654-22bc0d00-b83f-11e8-89d2-9f83436d25b9.png)
![image 7](https://user-images.githubusercontent.com/39734400/45547655-22bc0d00-b83f-11e8-9314-6ecce8aabb46.png)

**Comment by mukeem1** [comment]
Is it the single case or more

**Comment by crayonflakesmanu** [comment]
atleast 2.

**Comment by crayonflakesmanu** [comment]
some examples


B1-T119-2_3
B1-T129-2_3
B1-T130-2_3
B1-T133-2_3
B1-T134-2_3
B1-T136-2_3
B1-T141-2_3
B1-T143-2_3

**Comment by mukeem1** [comment]
we need to handle data gap for such cases as first image of these skus is null.
