### ISSUE TITLE
User Reported Problem - There should be an option of removing the user |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#51]
Partner : OIR, User : anshul.bansal@gmail.com 
Problem : Provide a static button at the bottom to remove the user. It should remove the user's roles from the selected company.
Router Link : /admin/manageusers/userdetails/02b335e9-8f6e-4089-80be-29ff5f9e2ecb

**Comment by mukeem1** [comment]
You can remove all the roles of the users to stop working
