### ISSUE TITLE
User Reported Problem - Return Items FC change DS_VIRTUAL |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#512]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 008b2e
008aus
008sqv
0049e0
008wty
008I09
008u80
007fml
008wtv
008u89
004yoh
008u8g
007nzf
008awg
0077y6
008sqp
008wv5
008tsk
006aqn
0077qm
008hqw
000v8j
008wsk
007fn1
007sgg
0025u8
002wga
008sms
008gdd
008wye
008zby
008ntr
008bv6
008hrb
008wu8
007gou
008u7y
008as7
008as3
008src
007v1f
008u6a
008lua
005zn0
008u5i
008u6d
008lrw
008u77
007fv7
008i3u
008umk
0079t8
008uct
008chg
008k9i
008goa
008ibw
008mo6
007jk5
008chl
0077xq
008m9l
007ngf
008sn2
008kf0
008cf3
007b46
0093x4
008qux
008zqp
00907q
008yc4
0075mc
002zai
008r1w
008cfs
008u4d
00473n
008qwh
004kee
004224
0068lx
007si9
0064o7
008uj2
0079p1
008gbv
008ubf
008tu4
008zr3
007fmj
008udf
008gob
00907n
001t8t
002nmn
008zso
004r8s
003u2w
008cig
008puy
008u6l
008uhk
008ezk
008u79
008ud7
007fjd
0093ya
008bkw
008djx
0043f8
0048xa
002c5o
00522j
001s0s
003ujo
003zbj
007nz2
005xaf
008ftd
00908h
00435j
007jg1
007aof
007an5
008hvs
000trb
0079vh
008knh
007pmd
007jma
002rjk
008ia3
003see
005ezg
008iby
008gpq
008uim
008mkr
0079ss
0044cz
004jfy
005yy5
00907l
008ui3
008zpm
008cs1
008yd5
007k1h
008zpz
008f3f
0093wm
008snq
008mkt
008ptz
0025ah

Router Link : /inventory/finditems

**Comment by Krn7210** [comment]
done
