### ISSUE TITLE
Item movement from Reserve Sold to Shipped is not recorded

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#514]
See the below example -
After being reserved sold on 29/7 , it is directly made available from shipped on 23/8.
Hoping it was shipped for some order and was issue a return before which it was made available on 23/8 but none of this was recorded.

![screen shot 2018-09-17 at 1 02 41 pm](https://user-images.githubusercontent.com/39734400/45610649-4a4ae980-ba7a-11e8-84d5-a707ecbcb58f.png)

**Comment by mukeem1** [comment]
This is the case where reserved sold items are  marked shipped from backend and later on this was scanned with a location so status  changed to available.
Yes, we need to put more events around the items for better understanding of data.
_Thank you._
