### ISSUE TITLE
User Reported Problem - Return Items FC Change DS_VIRTUAL |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#517]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 49X2772
265X11892
000W23
000KRG
000015
0001PU
000J7C
0032UX
006IT8
93X7752
36X2092
005DVD
0010KZ
006COX
003UZE
000HD9
000JLR
8846X66
228X10778
0051HN
002C5P
0075JY
004UM4
006HED
004MOZ
006LC3
004VN5
003QNK
005YQ5
006KO6
006980
0050XF
00441S
002O1Z
008NQZ

Router Link : /inventory/finditems

**Comment by akanksha-10** [comment]
done
