### ISSUE TITLE
Not able to upload DO with the attached excel

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#518]
![screen shot 2018-09-18 at 4 00 31 pm](https://user-images.githubusercontent.com/39734400/45683379-0e3e8400-bb61-11e8-8fd5-bd14c1be06fd.png)

[DO_157758.zip](https://github.com/StompMarket/helpdesk/files/2392365/DO_157758.zip)

**Comment by mukeem1** [comment]
it was something random. working fine in most of the cases.
