### ISSUE TITLE
User Reported Problem - Need to clean up the list of roles assignable |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#52]
Partner : OIR, User : anshul.bansal@gmail.com 
Problem : Also, stompmanager or catalogadmin should not be a part of this list at all. We also need to provide better intuitiveness to the name of the role to its actual mapping.
Router Link : /admin/manageusers/userdetails/02b335e9-8f6e-4089-80be-29ff5f9e2ecb

**Comment by k-abhinav** [comment]
This is partially done by @mukeem1, now handover to @mukeem1

**Comment by mukeem1** [comment]
done
