### ISSUE TITLE
User Reported Problem - listings issue in etsy |dearmonika786@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#523]
Partner : SI, User : dearmonika786@gmail.com 
Problem : i can not see listing in draft its very low count only 29 to 30 items in draft. usually +50 items hote hai nut 2 days ke count low hai.
Router Link : /inventory/finditems

**Comment by Ronit1234** [comment]
if ypu see again there is no listing in etsy account then you reopen it this issue
