### ISSUE TITLE
There is market for these trims however we are not able to manage inventory

### ISSUE THREAD

**Issue by AnshulVermaStomp** [StompMarket/helpdesk#531]
AMAZON.COM
113-3268981-0038652       NL-487
113-1763849-7557861       NL-423

AMAZON.UK
402-7362917-1823520             NL-488

**Comment by AnshulVermaStomp** [comment]
These items are missing

**Comment by mukeem1** [comment]
Multi Quantities items handling still pending.

**Comment by mukeem1** [comment]
Not handling this for now.
