### ISSUE TITLE
User Reported Problem - Ornamenta brand  |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#54]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : ornamenta brand is not available in feed 
Router Link : /home

**Comment by k-abhinav** [comment]
Duplicate Issue #72, So closing this issue.

**Comment by stompmahesh** [comment]
This is for Ornamenta brand , #72 for Oreleaa
