### ISSUE TITLE
User Reported Problem - Transfer id se item bik raha hai Limeroad main |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#543]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : JAE-1938 Bika hai  Order id 0038910389S3
 Transfer I.D 3450 Check 
Router Link : /inventory/fulfillmentcenter/5/transfers/2450

**Comment by akanksha-10** [comment]
The location of this itemnumber is BOX-142BX1I.
