### ISSUE TITLE
User Reported Problem - Amazon.in order id show nhi ho rhi hai |akashk02001@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#547]
Partner : OIR, User : akashk02001@gmail.com 
Problem : 406-5194031-9717131 --- 511736493870 -- 002V5X

Router Link : /catalog/brands/3/assembledskus/177221

**Comment by akanksha-10** [comment]
The order status of this platform order id is pending(0) in the database but in the Api orders the order status is shipped. That's why it was not displaying in the pending shipment.
