### ISSUE TITLE
User Reported Problem - Metrology |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#557]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Metrology detail at purchase level since this need in all E commerce  platform 
Router Link : /home

**Comment by stompmahesh** [comment]
Metrology detailed sticker -
Name and address of Manufacturer/Packer/Importer.
Country of origin
MRP.
colour
Quantity
