### ISSUE TITLE
User Reported Problem - Stomp error  |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#558]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : BeeRock ke item jo haam maga te hai bo Ship nhi hote
Router Link : /fulfillment/processShipment

**Comment by mukeem1** [comment]
To ship beerock items, transfer should be made for DS_IN shipping warehouse
