### ISSUE TITLE
Zephyrr Store- Ebay.com 

### ISSUE THREAD

**Issue by AnshulVermaStomp** [StompMarket/helpdesk#566]
In the description this content is coming in the listings. Please take off this content along with Jyoti's image 
----
About Sanskriti India

Hi! My name is Jyoti. I am a New Delhi based collector and seller of unique Indian Vintage items.

I have been selling vintage Indian items on eBay for more than 7 years and have been fortunate to be recognized as the best seller on eBay for stunning Indian fabrics like Sarees, Dupattas, Embroidered patches, Tops etc.

On May 2016, I was also awarded India's highest award for best online exporter from the Honoble President of India!

At my store, you are assured of highest quality merchandize and service you can find on ebay. I am very selective with my collection and keep only the freshest items on this store.

Any customer issues are taken with utmost seriousness. We have been very protective of our buyer's experience. Which is the reason we are consistently the highest quality seller on eBay for years

I hope you will find the perfect piece of Indian vintage heritage on my store. I love sprinkling a bit of India around the world. Thanks for sharing these joys with me. Namaste!!

**Comment by Ronit1234** [comment]
done
