### ISSUE TITLE
Ebay.com - Zephyrr - Even if item has single child then also variations are shown in the parent

### ISSUE THREAD

**Issue by AnshulVermaStomp** [StompMarket/helpdesk#568]
https://www.ebay.com/itm/Zephyrr-Saffron-Tibetan-Stone-Dzi-Beads-Necklace-Set-With-Earrings-For-Women/253895397817?hash=item3b1d5851b9:m:mtD2yGp6wbEM-nfp1IoKU1g&var=553196629703

https://www.ebay.com/itm/Ornamenta-Fashion-Handmade-Beaded-Long-Necklace-with-Metallic-Beads-for-Girls/253893220749?hash=item3b1d37198d:m:mvErlADDvyjy6ITZ1MT-AbQ&var=553193578286

**Comment by Ronit1234** [comment]
not possible from server side for this platform
