### ISSUE TITLE
User Reported Problem - Barcode not generating for FLEX |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#570]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : SK-1651
JAN-1487
BLT-53
BLT-52
BUTTON-197
JAE-3158
JAN-1721
JR-39
JAB-89
JHB-216
Router Link : /falite/falitebarcode

**Comment by mukeem1** [comment]
fixed
