### ISSUE TITLE
Potential Issue in last 30 day sale tab

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#577]
As per the data, surprisingly there is not SKU which has sold in last 30 days but is out of stock currently.

![screen shot 2018-09-27 at 12 45 47 pm](https://user-images.githubusercontent.com/39734400/46129150-65c0ac00-c253-11e8-9605-89368d856765.png)

Are we missing some data here?

**Comment by nishant1414** [comment]
issue rosolved
