### ISSUE TITLE
Pls add few columns in the last 30 day sales tab

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#578]
1. Product Code (Parent Code) - so that we can group style wise and see the sale.
2. Product Type

![screen shot 2018-09-27 at 12 48 01 pm](https://user-images.githubusercontent.com/39734400/46130160-32cbe780-c256-11e8-89b0-74d9610f6455.png)

**Comment by nishant1414** [comment]
added will be delievered in next release
