### ISSUE TITLE
KSET - Feed File - Changes in A.in Feed File

### ISSUE THREAD

**Issue by AnshulVermaStomp** [StompMarket/helpdesk#591]
Please check the same doc. Already discussed with Mukeem

https://docs.google.com/spreadsheets/d/11_yni9Xlq37TJxJp0BWl7mzkkO4VsmQi7qr9i2CMFZI/edit#gid=73526325

**Comment by mukeem1** [comment]
Propert types created. 
but how to mark properties mandatory in screen pending and need to figure out a way to show drop down of possible values in UI.
