### ISSUE TITLE
Potential inventory issue

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#592]
BOX20EX2 was reconciled on 26-Sept at our end
![screen shot 2018-09-30 at 9 30 57 am](https://user-images.githubusercontent.com/39734400/46253228-de15b000-c493-11e8-8d3f-35e8c74d5118.png)

Looks like Item - 009AYD did not come in the scan as its last scan date is 17-Sept or probably scan date is not recorded in case of reserved items.
![screen shot 2018-09-29 at 6 57 20 pm](https://user-images.githubusercontent.com/39734400/46253236-07364080-c494-11e8-8c94-05c0517887ae.png)

This is currently available as per stomp but not physically.

Suggestion - If a reserved item did not come in scan - don't make it available while swapping.

**Comment by mukeem1** [comment]
Should be checked in new version.
