### ISSUE TITLE
User Reported Problem - I have Already Listed these items  |singh.archna18@gmail.com 

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#598]
Partner : OIR, User : singh.archna18@gmail.com  
Problem : JRP45
JR-102
JRP44
JR-101
JRP43
JR-100
JR-99
JR-98
JAEP1473
JAE-3283
JAE-3282
JANP1070
JAN-1756
JANP1069
JAN-1755
JAN-1754
JANP1068
JAN-1753
JAN-1752
JANP1067
JAN-1751
JAN-1750
JANP1066
JAN-1749
JAN-1748
JANP1065
JAN-1747
JAN-1746
JAN-1745
JAEP1469
JAE-3276
JAE-3275
JANP767
JAN-1744
JANP1064
JAN-1743

Router Link : /channels/channels/10

**Comment by Krn7210** [comment]
these items are listed and are not coming in feed file
