### ISSUE TITLE
Need to move a variant

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#599]
Please move G17-KD38-2_3 from KDP511 to KDP220 and delete KDP511 (which would be empty).

Also, pls suggest how can we delete or move a variant in future?

**Comment by crayonflakesmanu** [comment]
Pls delete this variant - (KD-2232). Just ensure there is not inventory for this before deleting.
Since KFR-503 is already present in KDP220 (which is same 2/3 yrs size).

**Comment by Krn7210** [comment]
It is deleted
right now you cannot delete or move a variant
please open an issue if you want this functionality
