### ISSUE TITLE
User Reported Problem - item not available but sold     jan 1085 |deepakkumarpk112@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#602]
Partner : OIR, User : deepakkumarpk112@gmail.com 
Problem : hamare paas item available nahi hai phir bhi bik rahe hai kal 3 bike aur aaj 2      1 limeroad aur 1 flipkart pe    ham uski jagah kuch aur bhej rahe hai
Router Link : /inventory/finditems

**Comment by Krn7210** [comment]
inventory sync issue 
we are working on it
