### ISSUE TITLE
User Reported Problem - Need type of shipping in pick sheet for every orders |mjha8390@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#606]
Partner : SI, User : mjha8390@gmail.com 
Problem : Like - Standard/Expedited 
Router Link : /home

**Comment by mukeem1** [comment]
Shipping Method column already added in the picksheet and fetching data for some platform.
In case of ebay, data is not coming at fulfillment level. So @Ronit1234  you need to make changes and update it.

**Comment by Ronit1234** [comment]
Ebay not giving this ShippingDetail
