### ISSUE TITLE
other brand product appearing under our brand in this tab

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#607]
![screen shot 2018-10-02 at 12 14 29 am](https://user-images.githubusercontent.com/39734400/46308802-33f37080-c5d8-11e8-8f7e-9041293f51b1.png)

**Comment by mukeem1** [comment]
@akanksha-10  you just need to update data for such variants after coordinating with **Archana**

**Comment by akanksha-10** [comment]
This has been resolved. And it will be displayed in the next release.
