### ISSUE TITLE
Why do these variants have variant code in the sku name as well ?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#608]
![screen shot 2018-10-02 at 12 21 29 am](https://user-images.githubusercontent.com/39734400/46309161-2d192d80-c5d9-11e8-9b79-6b15d2033ecc.png)

**Comment by crayonflakesmanu** [comment]
+ these
![screen shot 2018-10-02 at 12 22 50 am](https://user-images.githubusercontent.com/39734400/46309208-52a63700-c5d9-11e8-80cd-332aa7aaebc7.png)

**Comment by crayonflakesmanu** [comment]
+ these
![screen shot 2018-10-02 at 12 24 02 am](https://user-images.githubusercontent.com/39734400/46309268-7e292180-c5d9-11e8-9438-5b038bf2eb1d.png)

**Comment by crayonflakesmanu** [comment]
+ these
![screen shot 2018-10-02 at 12 24 41 am](https://user-images.githubusercontent.com/39734400/46309311-9f8a0d80-c5d9-11e8-8583-757d8b68db27.png)

**Comment by crayonflakesmanu** [comment]
what is the suggested solution now? Shall I give you a excel with correction or you plan to release a feature to fix these sort of data issues?

**Comment by nishant1414** [comment]
Give us an excel with correction, we will update

**Comment by crayonflakesmanu** [comment]
Giving 1st iteration of bulk corrections in the product export excel. Pls connect with me or Jitender for any clarification.

[products_10_13_2018 (2).xlsx](https://github.com/StompMarket/helpdesk/files/2486432/products_10_13_2018.2.xlsx)
