### ISSUE TITLE
Partial FC-JIT Cancelled Orders are not being updated and keeps items reserved

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#633]
Example

2901538RXX4320413
4005078RPW103F928
2064196RRT50E8680
4579781RI16410539
5073770RXY2011754
6039076RSU4386116
1383047RRU35A0174
3754349RLU8396074
5401389RHY1AB0730
3870857RJX13C0230
4506612RBU5263648
6086224RNZ6270777
5979390RAZ152E041
2340969RPU3021975
4257012RMR31C3589

**Comment by akanksha-10** [comment]
[FC-JIT cancelled orders.xlsx](https://github.com/StompMarket/helpdesk/files/2459310/FC-JIT.cancelled.orders.xlsx)

What should I do with these reserved items?
