### ISSUE TITLE
Pls validate reserved items against these cancelled orders

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#634]
OrderID | Order Date | Order Status | Shipping Date | Count
-- | -- | -- | -- | --
1778819RPX74DA232 | 04/09/2018 | Delivered | B1-T109-4_5 | 1
4740248RT13474290 | 30/09/2018 | Cancelled | G1-Set5/20-3_4 | 1
1864478RXU9026551 | 07/08/2018 | Delivered | B1-SH19-2_3 | 1
496268RAZ66AE823 | 23/09/2018 | Delivered | B1-S2/2-7_8 | 1
5189166RPU7026339 | 05/08/2018 | Delivered | G1-KD1/1-6_7 | 1
4228447RTY85D0998 | 15/09/2018 | Cancelled | B1-SH31-6_7 | 1
5556603RKY21C8964 | 09/09/2018 | Cancelled | B1-T19-3_4 | 1
3947072RSR949C947 | 08/07/2018 | Delivered | G1-SH25-7_8 | 1
440804RI10126627 | 27/09/2018 | Cancelled | G1-Set5/26-2_3 | 1
3882704RXY818C283 | 15/09/2018 | Delivered | B1-T14-3_4 | 1
3791253RJ1203C759 | 29/09/2018 | Cancelled | B1-T163-7_8 | 1
4803035ROW109C570 | 19/08/2018 | Delivered | G17-LG2-18_24 | 1
5577331RPV1181204 | 09/08/2018 | Delivered | B1-T116-4_5 | 1
4803773RTU6267910 | 04/08/2018 | Delivered | G17-NS16-2_3 | 1
5373664RUY6046018 | 13/09/2018 | Delivered | G1-SKD1/12-3_4 | 1
1266277RJW3540717 | 21/08/2018 | Delivered | B1-T138-4_5 | 1
5734912RNZ6195428 | 23/09/2018 | Delivered | G17-LG10-18_24 | 1
4573644RO131A0729 | 30/09/2018 | Cancelled | G1-Set5/10-1_2 | 1
155040RQU53C2809 | 03/08/2018 | Delivered | G1-SKD1/14-6_7 | 1
2443549RT151E3421 | 02/10/2018 | Cancelled | G1-KD3/15-6_7 | 1
2383689RKU9181776 | 07/08/2018 | Delivered | B1-T108-7_8 | 1
4972707ROU5818084 | 03/08/2018 | Shipped | B1-T3-6_7 | 1
6126986RW1248E974 | 29/09/2018 | Cancelled | G17-LG36-4_5 | 1
1171871RC120EE516 | 29/09/2018 | Cancelled | G1-KD7-22-6_7 | 1
2610755RP10770599 | 27/09/2018 | Cancelled | B1-T173-8_10 | 1
5775163RL144EA194 | 01/10/2018 | Cancelled | B1-SH26-7_8 | 1
2619739RX124D0835 | 29/09/2018 | Delivered | G1-LG6-4_5 | 1
1931556RNU8310260 | 06/08/2018 | Shipped | G1-SH28-7_8 | 1
5806023RQZ71C2937 | 24/09/2018 | Cancelled | G1-KD1/12-4_5 | 1
3281226RVU1276217 | 30/07/2018 | Delivered | G1-KD6/7-1_2 | 1
1156787RTZ23B1298 | 19/09/2018 | Cancelled | B1-T14-4_5 | 1
6075326RTV72AC912 | 15/08/2018 | Shipped | B1-T116-3_4 | 1
5389643RJR703A226 | 06/07/2018 | Delivered | G1-KD6/6-2_3 | 1
3371996RNT30E7614 | 22/07/2018 | Delivered | B17-SH22-4_5 | 1
2624886RUU8B10093 | 06/08/2018 | Delivered | G1-NS6-4_5 | 1
1466053RQU4228712 | 02/08/2018 | Delivered | B1-T3-6_7 | 1
3409258RWT8478888 | 27/07/2018 | Delivered | G1-KWD1/12-2_3 | 1
262972RUU7002218 | 05/08/2018 | Delivered | G1-SH27-6_7 | 1
2888030RWZ3063714 | 20/09/2018 | Delivered | B1-SHO3-2_3 | 1
6371953RU13066156 | 30/09/2018 | Cancelled | G1-KWD1/12-2_3 | 1
1945405RVV4B04252 | 12/08/2018 | Delivered | G17-NS13-4_5 | 1
6040697RXU43FC329 | 02/08/2018 | Delivered | B1-T3-6_7 | 1
5780614RQT9132874 | 28/07/2018 | Delivered | B1-T73-3_4 | 1
324427RB11136377 | 28/09/2018 | Cancelled | B1-T16-7_8 | 1
3616281RM1639C822 | 03/10/2018 | Shipped | G1-KD3/3-3_4 | 1
4217613RPS7639570 | 16/07/2018 | Delivered | B1-T104-3_4 | 1
4516806RMZ8090979 | 25/09/2018 | Delivered | G1-SH24-4_5 | 1
2814787ROV607C022 | 14/08/2018 | Delivered | G17-NS35-4_5 | 1
6307956RSZ2096966 | 19/09/2018 | Cancelled | G1-KD6/6-4_5 | 1
868751RR1531B773 | 02/10/2018 | Cancelled | G17-LG13-18_24 | 1
3940512RQX500F457 | 02/09/2018 | Delivered | B1-SH78-3_4 | 1
2589794RA10150467 | 27/09/2018 | Delivered | B1-T118-7_8 | 1
2062968RMU90FA073 | 07/08/2018 | Delivered | G1-SKD3/3-4_5 | 1
2141081RXU90B8983 | 07/08/2018 | Delivered | B17-NS4-4_5 | 1
1344737RMS8105078 | 17/07/2018 | Delivered | B1-T104-6_7 | 1
4630412RPZ5570327 | 22/09/2018 | Shipped | G1-KD4/9-4_5 | 1
1853610RXZ1172440 | 18/09/2018 | Confirmed | B1-T14-7_8 | 1
5775163RM141D6225 | 01/10/2018 | Cancelled | B1-SH26-7_8 | 1
3529343RMZ830F535 | 25/09/2018 | Cancelled | G16-WNS8-2_3 | 1
5920124RTZ7717430 | 24/09/2018 | Shipped | B1-SH82-7_8 | 1
5073770RXY2011754 | 09/09/2018 | Shipped | B1-T102-3_4
6039076RSU4386116 | 02/08/2018 | Delivered | B1-T3-6_7
5401389RHY1AB0730 | 08/09/2018 | Cancelled | B1-SH75-7_8
6086224RNZ6270777 | 23/09/2018 | Cancelled | G1-KD7-21-6_7

**Comment by Krn7210** [comment]
[ReservedItemAgainstCancelledOrders.xlsx](https://github.com/StompMarket/helpdesk/files/2452849/ReservedItemAgainstCancelledOrders.xlsx)

**Comment by crayonflakesmanu** [comment]
What does this mean? 
Are the reserved items released? Is the integration with BT for cancelled orders working as per expected?
The excel only has status in 3 rows.

**Comment by Krn7210** [comment]
i have validated all the reserved items against the cancelled orders, I have marked missing those items
where ordereddate was greater than lastscandate and marked available those items where lastscandate was  greater than ordereddate.
