### ISSUE TITLE
How can a barcode generated item be available & reserved sold?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#635]
![screen shot 2018-10-05 at 10 03 08 am](https://user-images.githubusercontent.com/39734400/46516177-e3a13a80-c885-11e8-9a50-4e16886c5af8.png)

**Comment by nishant1414** [comment]
this item was scanned on barcode generated location by jitender.cf@gmail.com on 2018-02-12.
that's why this item was live.

Now we have handled this case, you can not scan item on this location.

**Comment by crayonflakesmanu** [comment]
This is as per the event log - the process we follow is to scan the box and then assign.
Can't help on this one since barcodegenerated location was allowed to be selected until now. Lets try to close these similar potential issue points.

**Comment by nishant1414** [comment]
ok

**Comment by crayonflakesmanu** [comment]
Still see some items in reserved status from this location. How come?

![screen shot 2018-10-15 at 10 24 09 am](https://user-images.githubusercontent.com/39734400/46930622-5a97b980-d064-11e8-8b92-8ebe05b1b38a.png)
