### ISSUE TITLE
User Reported Problem - Item Missing |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#636]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : from rack RACK159-H
 all 166 items are marked as missing on 04-10-2018, however all these items are available .Please check and share the details 
Router Link : /inventory/finditems/itemSummary/618043

**Comment by Krn7210** [comment]
These Items were marked as available by this id-deepakkumarpk112@gmail.com
on 05-11-2018
