### ISSUE TITLE
User Reported Problem - pending SHIPMENT |sumit89371@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#637]
Partner : OIR, User : sumit89371@gmail.com 
Problem : DATA DOWNLOAD IN EXCEL FROM THIS PAGE IS GETTING DUPLICATED FROM LAST DOWNLOAD 
Router Link : /fulfillment/processShipment

**Comment by mukeem1** [comment]
This download fetches same orders until orders appearing in this are marked as ship.
