### ISSUE TITLE
User Reported Problem - Cancel order on amazon |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#638]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : any order canceled on amazon after reserving the item is not healing back to available some item no (004B6Q
005UMQ
008AYU
007NY2
007NY3
007JFY
0049KH
0091I6
007NY9
007JGW
007O01
0017J7
008QTR
0093YH
008WSF
007JGY
7682X4
000Q6N
006HWJ
000UVC
003Y38
000LA9
008EKK
008BLE
008EKM
008P1J
008YEW
0079UA
008CIR
00529S
0064HT
008GCK
003G3V
002UYS
003PRB
0093ZC
008MJ1
007NWA
0091QJ
00093R
007NWB
008NVV
000Y73
0048PR
0046L6
8481X12
008YE6
008YAH
008I6V
000I4I
008FPV
006LBM
007SM8
0051EF
008E8W
004ZA3
008B1Z
008AZZ
008CHI
690X65
0097IE
005TOC
009A9J
001YSO
006CVQ
005P7M
0093YF
008IKV
004FPX
008IHL
003ZBM
008FYZ
8296X101
0099X3
002BLB
007MNU
0044J0
008ZPM
0099O9
008CGP
004MNC
004UD4
004NLM
0075DH
0091PB
00950I
008PYY
003DUF
008YD9
008WV5
008WRL
008T3V
0013ZL
008CJI
0064O7
0075DO
008Z6C
00950F
00950C
0091OT
008IOW
008WU4
006BT9
007FHA
925X3
001B0B
0091Q6
538X369
004P0Y
004FWA
0075DJ
0065T0
009CNJ
008FX7
0036C8
008AUP
006R60
0075DL
004HE0
009F1U
004RXL
006Q92
009E6F
002ASU
009ANS
0046L9
0043DV
009FVC
004NLX
001JYV
008ME6
008MEE
008ME9
008AZO
008MED
009ELI
009ELJ
0046Q4
002NQL
0044MD
0099Z0
0099N2
008CJM
008VW7
009G99
008UBF
004HDM
008X00
003QS7
009A83
8481X13
0061SB
0064XK
398X26193
009EK1
001YT8
008YFD
005PDY
008OHI
) 
Router Link : /inventory/finditems

**Comment by mukeem1** [comment]
done
