### ISSUE TITLE
User Reported Problem - Flipkart syn issue |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#64]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : all mention items quantity is not sync with portal count.
DRS-252
KTCS-108
DRS-212
KTCS-134
DRS-151
KTCS-102
DRS-168
DRS-98
DRS-279
SL-1723
DRS-241
KTCS-111
JAE-2621
JAB-127
JAE-2916
KHB-10
JAE-2939
KCS-22
JAB-146
DRS-240
BAG-395
JAE-2938
JHB-143
PA-410
KTB-8
KND-4
JHB-157
JAE-1872
KFR-203
JAE-2933
SL-1812
JAE-2687
JAE-2955
DRS-163
DRS-246
KCS-19
KTCS-91
DRS-210
DRS-149
KCS-35
KNC-16
JAN-326
DRS-207
DRS-181
DRS-242
KFR-197
DRS-154
BAG-315
PA-1179
DRS-227
KFR-449
KFR-438
KTCS-34
KND-9
JAE-1874
Jan-19
KTCS-32
KNS-75
KFR-288
KND-40
KTCS-56
KTCS-44
KLS-100
PA-197
KWD-25
KFR-125
JAE-285
NTP-230
KFR-389
KFR-286
DRS-165
NTP-263
PA-868
BAG-313
JAE-2950
JAE-2945
JAE-2948
JAE-449
NTP-524
KTCS-35
JAE-2917
JAE-2588
BAG-400
KTCS-98
KFR-145
JAE-2684
JAE-2926
JAB-147
JHB-207
JHB-147
PA-1279
JAE-2949
JAE-2958
JAE-2681
SL-754
JAN-1076
JAE-2935
KTCS-145
JAE-2953
KTCS-148
JAE-2930
SL-126
JAE-2927
JAE-2959
JAE-2931
JAE-2936
KTCS-147
JHB-195
JAN-1249
JAE-601
JAE-2961
JAN-546
KTCS-92
JAE-2920
JAN-1048
JAN-1440
PA-1435
JAE-2497
JAE-2957
BAG-314
JAE-2682
KTCS-113
KTCS-107
JHB-146
JAN-771
JAE-2963
JAN-575
JAE-2458
JAE-2915
JAE-2853
JHB-153
JAE-2951
JAE-2675
Jan-17
JAB-145
KHB-25
JAN-1443
JAE-2947
JAE-2934
JAE-2765
KTCS-110
JAE-2929
JAE-2620
JAE-2923
JAE-2952
JAE-2685
PA-135
JAE-2924
SL-1448
JAE-2544
JAN-1449
JAN-720
JAE-1604
JAE-2946
JAN-1173
SL-1473
JAE-2922
JAE-2925
PA-1483
JHB-144
KFR-430
KLS-78
JAE-2680
JAE-2964
NTP-272
JAE-1982
JAE-2846
JAE-2962
JHB-151
KTCS-150
JAE-2918
KTCS-151
JHB-145
JAN-505
SL-1884
BAG-374
JAE-2965
JAE-2956
JAE-2928
BAG-463
JAE-2954
JAN-1335
JAE-2960
JAE-2677
JHB-196
JAN-855
JHB-205
JAE-2676
JAE-2563
JAE-2944
 
Router Link : /catalog/brands

**Comment by k-abhinav** [comment]
some issue in webjob, fixed in 05/06/2018. Now running well.
