### ISSUE TITLE
User Reported Problem - Transfer ID 3528 |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#647]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Not able to Scan to location :Sumit chauhan 
Router Link : /inventory/fulfillmentcenter/5/transfers/2528

**Comment by Krn7210** [comment]
As per discussion with sumit chauhan issue was resolved
