### ISSUE TITLE
User Reported Problem - Combo |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#648]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Combo shipmarking not working properly E.G if combo have two variants and only 1 variant is scanned for packed this show all quantity is packed .. case discussed with nishant 
Router Link : /fulfillment/processShipment

**Comment by mukeem1** [comment]
resolved in current build
