### ISSUE TITLE
User Reported Problem - ISSUE IN PENDING SHIPMENT SCREEN  |deepakkumarpk112@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#656]
Partner : OIR, User : deepakkumarpk112@gmail.com 
Problem : FA lite orders are not showing on shipmark screen while i have uploaded csb file 
Router Link : /fulfillment/processShipment

**Comment by mukeem1** [comment]
It seems file was not uploaded successfully.  It was uploaded in our first attempt. Now orders can be processed.
