### ISSUE TITLE
User Reported Problem - WHEN CRATING A COMBO GET  ERROR  |lalittheboss.kumar@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#661]
Partner : SI, User : lalittheboss.kumar@gmail.com 
Problem : COULD NOT GET SKU BY NAME
Router Link : /catalog/brands/1/assembledskus

**Comment by nishant1414** [comment]
u were trying to create combo in sanskriti whenever skus was of zephyrr brand
