### ISSUE TITLE
None of the catalog links are working

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#675]
Leggings
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Leggings&productType=KLS&pageCount=1&isreplenishable=true&fc=cf_noida

Dresses
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Dress&productType=KD&pageCount=1&isreplenishable=true&fc=cf_noida

Sets (Boys & Girls)
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Set&productType=KSET&pageCount=1&isreplenishable=true&fc=cf_noida

Shorts 
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Shorts&productType=KSH&pageCount=1&isreplenishable=true&fc=cf_noida

Boys

Shirts
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Shirt&productType=KS&pageCount=1&isreplenishable=true&fc=cf_noida

Joggers
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Joggers&productType=STC&pageCount=1&isreplenishable=true&fc=cf_noida

Shorts
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Short&productType=KSH&pageCount=1&isreplenishable=true&fc=cf_noida

NightSuits
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Night&productType=KNS&pageCount=1&isreplenishable=true&fc=cf_noida

**Comment by nishant1414** [comment]
http://stompcatalog.azurewebsites.net/catalog.html?keyword=Leggings&productType=KLS&pageCount=1&isreplenishable=true&partner=CF

**Comment by crayonflakesmanu** [comment]
Pls keep SKU name in place of variant name(style code) 
Also, need a size column.

**Comment by nishant1414** [comment]
catalog links are working
