### ISSUE TITLE
User Reported Problem - Amazon.in main Transfer ID se item bik raha hai |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#680]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : JR-30  4 quntity bike haii transfer id hai 3616 
Router Link : /inventory/fulfillmentcenter/5/transfers/2616

**Comment by nishant1414** [comment]
you have scanned these items on location like 'transferid: -----', thats why these items became live.
always scan trasferred items on correct location.
