### ISSUE TITLE
User Reported Problem - Stomp issue |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#684]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : Stomp main bar-bar photo arahi hai shipmark karte samey 
Router Link : /amazonflex/temporder

**Comment by akanksha-10** [comment]
There is no such problem, it is just you hover on image and it opens up image modal. To avoid this, click on row not on image.
