### ISSUE TITLE
Wrong pricing

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#687]
https://www.amazon.in/CrayonFlakes-Navy-Stripes-Sleeves-Shirt/dp/B07FMY3Q2F/ref=sr_1_1?ie=UTF8&qid=1539925357&sr=8-1&keywords=crayonflakes&th=1&psc=1

https://www.amazon.in/CrayonFlakes-White-Check-Sleeves-Shirt/dp/B07FMZ96ZH/ref=sr_1_5?ie=UTF8&qid=1539925357&sr=8-5&keywords=crayonflakes

https://www.amazon.in/CrayonFlakes-Navy-Stripes-Sleeves-Shirt/dp/B07FMV749Q/ref=sr_1_23?ie=UTF8&qid=1539925409&sr=8-23&keywords=crayonflakes

**Comment by nishant1414** [comment]
can you send skus of these items and their correct price the we can check.
