### ISSUE TITLE
User Reported Problem - Amazon.in Shipmark problam |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#689]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : Item scan but not Packed 
408-6949567-7976339  item no.008Q36
7-8 baar scan karne par packed main jarahe hai
Router Link : /fulfillment/processShipment

**Comment by Krn7210** [comment]
we are rewriting the system and 
all these kind of bugs will be resolved in next release
