### ISSUE TITLE
Why is stomp allowing us to scan wrong items in orders - Another issue from FC-JIT

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#691]
Order ID - 6445871RX25478559

Ordered Item - G1-Set5/13-3_4
We sent - G1-S1/1-3_4

https://firstcry.s3.amazonaws.com/osr_6445871RX254785592_2298217_ret3_20181021_134136.jpg
https://firstcry.s3.amazonaws.com/osr_6445871RX254785592_2298217_ret2_20181021_134330.jpg
https://firstcry.s3.amazonaws.com/osr_6445871RX254785592_2298217_ret1_20181021_134401.jpg

Why is stomp allowing us to do so ? and the fact is we are scanning every single apparels order in stomp before sending.

**Comment by Ronit1234** [comment]
![image](https://user-images.githubusercontent.com/33680616/47421174-ad2c5080-d79d-11e8-960c-1778086f5a47.png)

As we have checked and found  that stomp is showing an error popup while you trying to pack different sku's item with the order. In this case i think you missed the error and send the itemnumber of other sku.
for your kind information please check screenshot in attachment.

**Comment by crayonflakesmanu** [comment]
Yes, I know stomp ideally gives that error and looks like this case has been different.
Pls see this order screenshot - why is an item available ?

![screen shot 2018-10-25 at 4 02 32 pm](https://user-images.githubusercontent.com/39734400/47494497-6ad34400-d86f-11e8-9f13-51ae457ec0fc.png)

on this screen it shows this-

![screen shot 2018-10-25 at 4 04 22 pm](https://user-images.githubusercontent.com/39734400/47494560-98b88880-d86f-11e8-9c4d-3a2a3822c7eb.png)

**Comment by crayonflakesmanu** [comment]
We have marked this order shipped. Can you pls confirm this?
