### ISSUE TITLE
This B2B order not reflecting - 184718R850DE1D

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#696]
Order ID - 184718R850DE1D
Shipping Below items -
009B6O
009B5I
009B6U
009B63

Shipping Ref - 111187311644

Pls analyse why is this order not reflecting in stomp.

**Comment by Ronit1234** [comment]
Can you please provide us some other b2b orders in  your channel

**Comment by Ronit1234** [comment]
this order is solved...
for further investigate pls provide other b2b order

**Comment by crayonflakesmanu** [comment]
All FC-JIT orders that end with "D" are B2B orders.

**Comment by nishant1414** [comment]
As I have checked and found all FC-JIT B2B orders are reflecting in stomp.

please check the screenshots.
![image](https://user-images.githubusercontent.com/35092628/47482198-79abfd80-d853-11e8-9b9d-8fd96894e51e.png)

![image](https://user-images.githubusercontent.com/35092628/47482215-86c8ec80-d853-11e8-9570-eb12d522ba27.png)

**Comment by crayonflakesmanu** [comment]
I gave a particular B2B order which was not reflecting at that time. It would be fruitful to analyse the time this order was created in stomp and order date. I can give screenshot of such orders in future for you.
