### ISSUE TITLE
User Reported Problem - Not able to upload images for KS-333 |manu@crayonflakes.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#7]
Partner : CF, User : manu@crayonflakes.com 
 Problem : After selecting 2 images, the upload/save icon is disabled.
 Router Link : /catalog/brands/5/products/193008/variants/204757

**Comment by anban4u** [comment]
Neetu please look into this and provide resolution.

**Comment by neetusingh1993** [comment]
Will be resolved by today
