### ISSUE TITLE
User Reported Problem - item not Available   but sold    jan 1232 |deepakkumarpk112@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#700]
Partner : OIR, User : deepakkumarpk112@gmail.com 
Problem : item  Available   nahi hai ds me phir bhi ds se bika hai
Router Link : /inventory/finditems

**Comment by Krn7210** [comment]
jan-1232 is available on DS_in 
and it was last scanned on 2018-10-21 10:56:56.527
that is it is available
