### ISSUE TITLE
User Reported Problem - Amazon.in ki order id show nahi ho rahi hai naa hi picksheet main item arahe hai |sumitkumar7102000@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#701]
Partner : OIR, User : sumitkumar7102000@gmail.com 
Problem : 404-4745393-7067563
402-8792023-3932330
405-2044325-7476367
407-3934468-3206737
404-7183795-0212330
405-7643435-6890709
406-0360576-3068324

Router Link : /amazonflex/temporder

**Comment by Krn7210** [comment]
stompmarket only show orders whose order status is confirmed
404-4745393-7067563
405-7643435-6890709
the order status of these two order is shipped so it is not showing these orders on stompmarket

and the order status of other orders is confirmed so the  other orders are showing in stompmarket
