### ISSUE TITLE
FC-JIT order on stomp showing extra items than actual

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#702]
Order ID - 2480558RQ360CD020
We are shipping below 2 items:
008Q0V
009FZ8
Shipping Ref - 111187343428
but it shows 3 items on stomp.

**Comment by Ronit1234** [comment]
Browntape has attached 3 items against this orderId, so stomp processed 3 items and reserved it

**Comment by Ronit1234** [comment]
as we have checked and found that we are shipping all the items attached with the orders in case of partial order shipment.,
now we done correction in the code, this change will be up in next release.
 hope next release will solve your most of the issues.
