### ISSUE TITLE
User Reported Problem - Variant change ....JAE-969 |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#705]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 009YAE
009YAF
009YAG
009YAH
009YAI
009YAJ
009YAK
009YAL
009YAM
009YAN
009YAO
009YAP
009YAQ

Router Link : /inventory/changeitemstatus

**Comment by Krn7210** [comment]
done
