### ISSUE TITLE
Amazon sale not appearing in our partner sale

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#707]
![screen shot 2018-10-25 at 4 07 39 pm](https://user-images.githubusercontent.com/39734400/47494764-0a90d200-d870-11e8-8777-66dc3946d0c1.png)
![screen shot 2018-10-25 at 4 07 32 pm](https://user-images.githubusercontent.com/39734400/47494765-0b296880-d870-11e8-87f2-07807ec91b28.png)

**Comment by crayonflakesmanu** [comment]
[PartnerSale_25_10_2018.csv.zip](https://github.com/StompMarket/helpdesk/files/2514443/PartnerSale_25_10_2018.csv.zip)

**Comment by nishant1414** [comment]
I know amazon sale  were not appearing in this report.
we have added other platforms sale in this report
and two more report added in this tab,
1st is top 50 selling skus
2nd is  hot arrival skus.
you will get all the reports in next release
