### ISSUE TITLE
Are items from Status report, All status - giving result across warehouse ?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#708]
![screen shot 2018-10-25 at 4 31 28 pm](https://user-images.githubusercontent.com/39734400/47496055-69a41600-d873-11e8-9671-ab642b8a737d.png)

These items are not present in our warehouse.

**Comment by nishant1414** [comment]
this report is giving result across all warehouses.

**Comment by crayonflakesmanu** [comment]
Pls check if this is by design. Because this will make the only report with one option (All) giving data across warehouse otherwise all reports & options giving data in same warehouse.

**Comment by nishant1414** [comment]
As I have checked but could not found any events of these items.
but this report is giving result  only in selected warehouse.

**Comment by nishant1414** [comment]
Now this report deos not exist in system. 
So we are not working on this issue.
