### ISSUE TITLE
User Reported Problem - Shipmarking Issue |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#719]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Every day we face issue while shipemark 5-10 orders need to send to IT team for shipmarking , this lead to process GAP. Need a proper solution for this. Akansha Have all the data which all Items having issue and why 
Router Link : /inventory/finditems

**Comment by mukeem1** [comment]
hopefully problem resolved fully in new version
