### ISSUE TITLE
User Reported Problem - paytm |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#72]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Oreleaa brand not visible for feed 
Router Link : /channels/channels/36

**Comment by k-abhinav** [comment]
I will create the all existing SKUs of Zephyrr into the Oreleaa, then the user can create the feed files through the dashboard.

**Comment by nishant1414** [comment]
Oreleaa brand has been created.

**Comment by akanksha-10** [comment]
This issue has been resolved.
