### ISSUE TITLE
User Reported Problem - FC change DS_VIRTUAL...& Status change (status 2) |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#724]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 0013zx
667x156
008mov
004o4x
8006x24
008p35
008pcb
001429
008vvw
008moh
007fdd
643x11
0005fz
008p9h
00772z
000obd
007fd8
007au4
643x9
690x63
0005fz
008p3v
008mp7
002s9u
706x114
007at6
0001z8
007bfh
0003l4
008t44
004c70
007735
0004vz
005a1q
8004x48
0004vs
008p34
8884x39
003v0d
008fzn
008t3w
008mm2
008cu8
0017nv  

Router Link : /inventory/fulfillmentcenter/204/transfers/new

**Comment by Krn7210** [comment]
done
