### ISSUE TITLE
User Reported Problem - FC change DS_IN.. |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#727]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 009DLM
009T0M
009RFF
009T0E
009FA0
009RF0
009RDE
009T0I
009T05
009RD6
009DLN
009T0J
009RD7
009T0G
009DLR
009RDD
009T0K
009T0F
009DLL
009RD9
009T0C
009T0H
009T0B
009FA2
009FA4
009FA1
009F9Z
009FA3
009DLQ
009RDA
009F9Y
009DLS
009FA5
009RDC
009T07
009RDB
009T09
000UPB
0036CS
008P9A
000UOQ
005TYP
009CQ6
000UPD
004TEI
004TEI
000UP7
005TXR
004TEG
004PTK
008FYH
004BPC
002S6J
000UQ7
0078WX
003GJ8
008MP1
000UP0
0003MT
009CDF
008FYN
009CPK
000UPH
008ODD
005TY5
008VWT
396X25812
008MPX
000JI2
008OE7
008MP3
008P8X
396X25809
008LXF
008P8R
008VWX
008PCH
008VWK
0003MY
005TZF
000XK8
0091IU
0078WP
009CNS
009X2H
009X2G
009X2J
009X2I
009X2F
008FYQ
0095W8
875X92
920X151
009CCR
009CNV
008MPC
008PC5
008LX0
003SGC
000UP6
008MOS
005TYO
008LX1
000UOV
0003MR
008PC1
008ODU
008LX5
009CQ2
008P9E
009CDK
008Q39
396X25818
008MPN
000UPX
000XK7
0095WD
000BOD
0095WG
008P9D
836X80
875X89
000BM7
009COX
000UPZ
000UQ0
000UOP
000JJC
000UQ8
009CO0
008MOR
009CCH
008MOB
008LWJ
008VWC
005TXM
0036CE
000UP3
008Q35
008ODP
000UQ5
008LYC
000UPA
000UOR
000UOX
0091IT
001NPI
009CD0
0036CO
008PBM
005TZ2
0078WT

Router Link : /catalog/brands/11/products/201992/skuSearch/variants/216591

**Comment by Krn7210** [comment]
done
