### ISSUE TITLE
Searching orders by date on Channel Screen - removes today's orders

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#736]
![screenshot 2018-11-02 at 9 53 40 am](https://user-images.githubusercontent.com/39734400/47893847-2f470400-de85-11e8-8d29-a26eea229444.png)

![screenshot 2018-11-02 at 9 54 33 am](https://user-images.githubusercontent.com/39734400/47893856-44bc2e00-de85-11e8-9364-9dbe3fbcddcf.png)

**Comment by 044aman** [comment]
this screen is completely changed
