### ISSUE TITLE
Last 30 days sale on channel tab, is across channels ?

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#738]
This 30days sale seems to be across channels and not on the particular channel opened. Is this by design or a bug ?

![screenshot 2018-11-02 at 12 26 52 pm](https://user-images.githubusercontent.com/39734400/47898135-97ecab80-de9a-11e8-9ff3-21771e874108.png)

**Comment by nishant1414** [comment]
the last30daysSale report is showing sale only on purticular channel.
