### ISSUE TITLE
User Reported Problem - Image view |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#747]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : whenever mouse pointer rome from any Image this open image as thumbnail.
Router Link : /catalog/brands

**Comment by akanksha-10** [comment]
There is no such problem. This is the functionality that has been added for viewing thumbnail images on hover.
