### ISSUE TITLE
paytm seller requirements

### ISSUE THREAD

**Issue by nishant1414** [StompMarket/helpdesk#766]
1 - Inbounding - 
    1 -  bypass - location based items  inbounding and their tracking .
                      - Reconciliation of location based inbounding and .
                      - access.  -- not  now
2 - Order - 
   1 - picksheet - location, sku and quantity wise picksheet summary
                        - combo items picksheet 
                        - multiple items picksheet
                        - single item  picksheet

3 - combo transfer prices - not now 
4 - location based outbounding and reconciliation.
5 - invoice download -  sorting on sku level and then carrier level and then item level(single multi, combo) alphabetically.
6 - bulk return inbounding .

**Comment by anban4u** [comment]
This has been completed and delivered
