### ISSUE TITLE
User Reported Problem - fc & status change ds_virtual , status 2 |shashikala251@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#767]
Partner : OIR, User : shashikala251@gmail.com 
Problem : 007nyy
003xdv
004iqx
0033ia
007nvr
008mac
008az8
005qzi
007ntz
000i4u
0095sj
005d1d
004u48
0095r3
00490o
008mkq
007ns3
0044ve
004scm
008efj
008wy6
008wu9
006cus
006s6l
008b88
006auc
008bar
0049ti
00367y
0095ts
003e7c
003tp5
008gmr
008axn
003yb7
0098fv
00763i
0065o7
008wuk
006r8x
0097ju
008np0
008sr9
005bt6
9514
0063yy
007s8h
007nts
006a84
003r0l
0095ri
007k1g
006asz
00459p
007jeu
006akn
0044mx
008ia9
004mnw
008tz2
003ybk
5982
008zch
0064we
003mrs
0050f9
006lau
9537
0098dr
004yw4
0097hg
008sp0
007nxb
008sr8
007gq1
003cyg
007v5l
003fxg
008ub9
0019iu
0065p1
008by9
008zse
008bmk
008sox
0099oo
008zcr
008noa
004ko1
9511
008e8o
0093vq
007jkb
006s1u
007jep
005ew1
006knx
008qrh
005jky
001ats
00623z
005kv8
0041th
001az5
0093vh
008twl
0017j8
008awj
7640
008eb5
0046l0
0095u1
9550
008zqc
00954r
008qxa
003mqj
007jh6
005oz6
004fx0
008ul4
00263k
003chu
008m9e
001fw1
008hst
0098ex
000i56
005ox3
0098g9
0048y4
00952c
008yaf
008iqp
6414
008df2
004jb6
007o1q
008uec
007v2q
9546
0093uh
00643s
007shr
004fj1
003o9l
004mnj
0099mq
001zpw
004obw
0095sc
004jth
005yq7
000T66
0079wp
9513
0042c1
008wt0
000ie9
008knl
006acw
008trw
008ez9
003fli
0093zr
0099xl
004t95
0095t0
008qux
008x0b
0044c3
009amz
008cal
0098h5
0064zr
9.80E+10
006s5d
0099eq
00675b
0095u0
0046q5
008zc4
008iaa
009a9b
007nso
0093x3
0047yw
007nuf
0099f8
00227n
0020in
 008yc4
0098ff
009a6o
0093vg
008ykd
00443i
007nz6
008ts6
0040fd
4420
9549
0098fj
008zcn
 0098gx
005uia
0063ul
004qfq
008wsx
0099w3
008hdf
0065xg
008huq
008ihj
004vax
006qhl
008lu4
004jwn
008ufl
003r0m
003goa
008gbr
007sii
0091on
007jmv
005ew4
004z26
008wvv
008gg2
003pmw
008u5c
0097kw
0095qw
003cdr
00953m
007ao2
004qk5
004qfy
00952r
007ao0
007nan
0097gc
008e1k
009a6m
008eb8
0047vg
006jxi
008ukx

Router Link : /inventory/barcodes

**Comment by Krn7210** [comment]
done
