### ISSUE TITLE
Need coverage Query

### ISSUE THREAD

**Issue by vermaanshul** [StompMarket/helpdesk#774]
I have created Manually but this needs to be provided by query:

SKU
Qty - Sorted on Qty
Sales - Last 60 days sales ( on Any platform)
Amazon.in - If Listed then Already listed else blank
Amazon.com - If Listed then Already listed else blank
Amazon.co.uk - If Listed then Already listed else blank
Flipkart - If Listed then Already listed else blank

**Comment by nishant1414** [comment]
given
