### ISSUE TITLE
Registration Issue on Stomp

### ISSUE THREAD

**Issue by Arushi1Saxena** [StompMarket/helpdesk#83]
I'm getting this error while registering on app.stomp.market.

![stomp registration error](https://user-images.githubusercontent.com/39825817/41144192-b3703d8a-6b19-11e8-8d1e-f431072a7ec1.png)

This is happening when I tried to report the above issue.
 
![image](https://user-images.githubusercontent.com/39825817/41144250-ee7df53e-6b19-11e8-888f-ffc4ca49b58f.png)

**Comment by mukeem1** [comment]
Here can be two type of new users
1. Who wants to join StompMarket as Partner Then New company creation is required.

2. User can be a member of a Parnter.

We are working for onboarding
