### ISSUE TITLE
User Reported Problem - Biosports is interested in implementing system |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#87]
Partner : OIR, User : anshul.verma@sanskritii.com 
Problem : Please speak with Vikas when you have time
Router Link : /home

**Comment by k-abhinav** [comment]
give me the contact number of Vikas

**Comment by anban4u** [comment]
This has been in operation now. Deepak and Mahesh are getting this done. Transfering this to Anshul Verma.
