### ISSUE TITLE
User Reported Problem - Flipkart APIs - Please note..URGENT |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#876]
Partner : OIR, User : anshul.verma@sanskritii.com 
Problem : 
 Dear Seller,

You need to upgrade the Flipkart Seller Hub Orders API to the latest version (V3). This will give you the capability to process multiple orders to the same customer in one shipment, which in turn will help you save logistics costs. 

Click here to upgrade

Note: The older version of API will not be supported by Flipkart, effective January 31, 2019.

Warm regards,

Flipkart Seller Hub

Router Link : /home

**Comment by Ronit1234** [comment]
done
