### ISSUE TITLE
User Reported Problem - Bar code  |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#879]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : bar-code printing still is a problem for qnbz,FBA,Cloudtail, FA_oir
Router Link : /fulfillment/fcs/5/packstations/3

**Comment by Krn7210** [comment]
screen for printing barcodes has been added
