### ISSUE TITLE
Filters not working properly

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#88]
Adding a value in filter box and clicking refresh and then removing the values, clears the list at the bottom.

**Comment by crayonflakesmanu** [comment]
Steps to replicate -

1. Type a word which does not exist in the list.
2. Select all the letters of this word and delete.
3. List below does not gets refreshed.

Looks like the event is binded to type/delete of single characters.

**Comment by mukeem1** [comment]
got your issues. we are working around it.

**Comment by mukeem1** [comment]
mat table filter issue.
will check it up
