### ISSUE TITLE
Why are selling accounts appearing twice on this report

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#897]
![screenshot 2019-01-30 at 9 57 52 pm](https://user-images.githubusercontent.com/39734400/51996272-6e174500-24da-11e9-9b8c-f3c14efaa3ec.png)

**Comment by nishant1414** [comment]
this data is grouped by currency and selling account,
thats why its coming twice.
in first row currency is null and at 2nd currency is INR.
