### ISSUE TITLE
User Reported Problem - Need status wise Report |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#908]
Partner : RBS, User : mahesh.stompmarket@gmail.com 
Problem : Need status wise warehouse report 
Router Link : /catalog/brands/29/products/227365/variants/242111

**Comment by maheshstomp** [comment]
Please provide status wise Inventory report so we can track inventory Health.
Live Inventory 
Reserved Inventory 
Missing Items 
Damaged Marked

**Comment by akanksha-10** [comment]
Already in the system.
