### ISSUE TITLE
Stock in house missing from this report

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#913]
![screenshot 2019-02-01 at 5 43 10 pm](https://user-images.githubusercontent.com/39734400/52122482-295dec00-2649-11e9-8913-7db3cb167a7d.png)

**Comment by nishant1414** [comment]
we cant add stock in this report now, but in other reports i have already added. 
in top selling skus, and hot arrivals  i have added stock.
