### ISSUE TITLE
User Reported Problem - On hot arrivals sales report..Images don't appear |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#919]
Partner : TJ, User : anshul.verma@sanskritii.com 
Problem : On hot arrivals sales report..Images don't appear
Router Link : /home

**Comment by nishant1414** [comment]
Images are appearing on every report .
In case if we dont have image of skus in database then images dont appear.
please check.
