### ISSUE TITLE
Having option to go to catalog page of a particular variant from the inventory screens.

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#92]

**Comment by mukeem1** [comment]
No such feature available in current working app.
@crayonflakesmanu  can you explain your case so that we could understand it

**Comment by crayonflakesmanu** [comment]
From the inventory reports - we can view particular SKU with image. This SKU row in not clickable. If there is an option to go to the catalog page of a particular variant directly to fix any issue - would be super helpful.
Explaining with a image
![screen shot 2018-06-11 at 1 04 34 pm](https://user-images.githubusercontent.com/39734400/41218872-35585d3e-6d7a-11e8-927f-4731d37f6894.png)


This was discussed with Abhinav & Anshul last week.
