### ISSUE TITLE
User Reported Problem - Sales Mails for Cartel Members in Stomp - Data Wrong |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#921]
Partner : OIR, User : anshul.verma@sanskritii.com 
Problem : Data is not correct. i.e. Beerock...we have sold close to 50 items yesterday but as per daily sales mail today it is showing 15 items only
Router Link : /home

**Comment by Krn7210** [comment]
duplicate issue
