### ISSUE TITLE
User Reported Problem - Image of sku not available |anshul.bansal@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#923]
Partner : AESPL, User : anshul.bansal@gmail.com 
Problem : The top selling sku report does not show image. Please fix
Router Link : /home

**Comment by nishant1414** [comment]
there are 1139 skus of AESPL_BRAND but we have images only for 146 skus.
and images of these skus are appearing in reports  if we have in database.

**Comment by nishant1414** [comment]
we required images of remaining skus.
