### ISSUE TITLE
Orders should be sorted date wise in descending order with date column visible by default

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#925]
1. Date column should be visible by default.
2. Orders should be sorted date wise in descending order.

![screenshot 2019-02-05 at 1 30 09 pm](https://user-images.githubusercontent.com/39734400/52259906-367d2280-294a-11e9-825a-5d034f2f4c8b.png)

**Comment by anban4u** [comment]
Agreed. Akanksha, can you correct

**Comment by akanksha-10** [comment]
This issue has been resolved and will be displayed in the next release.
