### ISSUE TITLE
User Reported Problem - Increase Title character limit |arushi2stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#926]
Partner : OIR, User : arushi2stompmarket@gmail.com 
Problem : Please increase title character limit from 80 characters, I miss out important keywords due to this. Jyoti also suggested this.
Router Link : /home

**Comment by anban4u** [comment]
Lets discuss this as this has an impact on ebay which has the 80 character limit.

**Comment by Krn7210** [comment]
it can be done because it will affect ebay
