### ISSUE TITLE
User Reported Problem - Search Items  |mahesh.stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#934]
Partner : OIR, User : mahesh.stompmarket@gmail.com 
Problem : Search item not searching any item other then Jan and JAE
Router Link : /inventory/finditems

**Comment by mukeem1** [comment]
@mahesh.stompmarket@gmail.com
I couldn't find any case as it is working fine. if you face this problem again. please provide that particular itemnumber
