### ISSUE TITLE
User Reported Problem - Bug |sumit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#935]
Partner : AESPL, User : sumit.whitecherry@gmail.com 
Problem : 30 Orders in the system but when creating batches only 1 order is coming...Batch id 549 / 548...urgent hain...jaldee theek karon
Router Link : /fulfillment/fcs/217/packstations

**Comment by Ronit1234** [comment]
we watch it on this
