### ISSUE TITLE
User Reported Problem - This PID Is not accepted in stomp |mohit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#940]
Partner : RBS, User : mohit.whitecherry@gmail.com 
Problem : 210214324
204933485
217364891
217364889
215938683
212452364
202896239
202896237
215938677
215932232
215932235
205086404
212452363
215938682
216064333

Router Link : /inventory/fulfillmentcenter/215/purchase/new

**Comment by Krn7210** [comment]
skus with this name are already available
