### ISSUE TITLE
User Reported Problem - I want option to add channel myself |sumit.whitecherry@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#950]
Partner : AESPL, User : sumit.whitecherry@gmail.com 
Problem : I want option to add channel myself
Router Link : /channels/channels

**Comment by anban4u** [comment]
Nishant please get this resoled today

**Comment by nishant1414** [comment]
We have given option to add new channel.
please go to the channel -> channellist -> and click add channel button.
