### ISSUE TITLE
User Reported Problem - Tjori - Report - Brand wise sale in last 30 days |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#957]
Partner : TJ, User : anshul.verma@sanskritii.com 
Problem : It indicates sales of 38 items in stomp...However when I check on A.in ..It indicates 110 Orders...Please fix the data error
Router Link : /home

**Comment by anban4u** [comment]
Check now that we have solved the fba order variant problem

**Comment by nishant1414** [comment]
I have checked and solved this bug. now you can see actual sale of brand here.

**Comment by nishant1414** [comment]
bug fixed and will be delivered in milestone 1.3
