### ISSUE TITLE
User Reported Problem - Zephyrr Store> EBAY > Sanskriti India  |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#959]
Partner : SI, User : anshul.verma@sanskritii.com 
Problem : Data on dashboard not appearing
Router Link : /channels/channels/16

**Comment by anban4u** [comment]
I think the problem here could be due to channel sync issues instead of data issue. Need to check and if needed reassign to ronit
