### ISSUE TITLE
User Reported Problem - Whitecherry Team needs Meesho as a selling Platform |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#963]
Partner : AESPL, User : anshul.verma@sanskritii.com 
Problem : Please add it. Also shouldn't there be an option to add Manual orders as a selling platform?
Router Link : /channels/channels/new

**Comment by anban4u** [comment]
Agreed. @nishant1414 . I think you have already done some work here. Please close if already resolved
