### ISSUE TITLE
User Reported Problem - Need inventory / stock on this screen |anshul.verma@sanskritii.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#964]
Partner : OIR, User : anshul.verma@sanskritii.com 
Problem : Need inventory / stock on this screen
Router Link : /home

**Comment by vermaanshul** [comment]
In sales report section:

For top selling and hot selling SKUs - Also Need stock

**Comment by anban4u** [comment]
Ok. Assigning this to @nishant1414

**Comment by nishant1414** [comment]
stock added in home page reports.

**Comment by nishant1414** [comment]
this fix will be delivered in milestone 1.3 on 28th feb.
