### ISSUE TITLE
Orders not in batch

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#972]
All these orders not in batch .

406-1521932-9718761
406-3517503-6870769
171-4563336-8571518
405-5012505-3858703
407-1642857-5066706

**Comment by anban4u** [comment]
@Krn7210 Please check and let me know why these didn't reach the batch. Take @Ronit1234 help as required.

**Comment by Krn7210** [comment]
All orders are reserved in QNBZ So you have to create batch for QNBZ
