### ISSUE TITLE
Replenishment Report

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#973]
1. Do This report Include/Exclude canceled orders/PO .
2. How this capturing combo sale. 
3. From Which Warehouse Inventory has mapped (Eg. Brand can have multiple warehouse, May want to include or exclude to Plan replenishment  ) 
4. Find Duplicate row level for same SKU and Platform(Screenshot attached).
![duplicate](https://user-images.githubusercontent.com/47552051/52897177-8041f480-31f7-11e9-8c30-408e687a849f.PNG)
![duplicate1](https://user-images.githubusercontent.com/47552051/52897180-859f3f00-31f7-11e9-9727-7e9f7fe061be.PNG)

**Comment by anban4u** [comment]
Lets solve this at high priority as it impacts business continuity

**Comment by anban4u** [comment]
@vermaanshul need your opinion as well on the correctness of this data

**Comment by nishant1414** [comment]
1 - this report is capturing combo sale.
2 - this report exclude cancel orders.
3 - now this report have inventory only in partner warehouses.
4 - duplicate rows have been removed.
