### ISSUE TITLE
Cancel Order- Inventory Issue

### ISSUE THREAD

**Issue by maheshstomp** [StompMarket/helpdesk#974]
at amazon if order got cancelled, Item is still on Reserved sold status. screen shot attached for one order and some order id and item no mention below , Please check.

Order   id | Item
-- | --
402-4976605-4814749 | 00ANIN
402-1426705-6753927 | 00A5UB
402-1841055-0142760 | 002O2E
405-5012505-3858703 | 8746X24
408-0159728-2869112 | 0050G2
408-6744253-3465144 | 00A7UX
408-6744253-3465144 | 00A8IB
408-8915055-7628300 | 002XUZ
408-8915055-7628300 | 00A7UW
404-2679824-2260303 | 00264T
405-8845161-8992336 | 009Z6R
405-8845161-8992336 | 00B260
406-1272717-0121927 | 00TS6D
406-1272717-0121927 | 00TS6C
407-4457363-6921156 | 010TNK
408-9935439-6655501 | 7844X1
408-0853959-8669907 | 00AS7W
404-2940751-7764340 | 008EW0

![amazon order](https://user-images.githubusercontent.com/47552051/52897625-bb92f200-31fc-11e9-9068-90f5dea4b4c0.PNG)
![item status](https://user-images.githubusercontent.com/47552051/52897651-f4cb6200-31fc-11e9-870b-0685dddf788a.PNG)

**Comment by anban4u** [comment]
Cancelled items should get available. This is critical

**Comment by Ronit1234** [comment]
it is resolved but previous data is untill same
