### ISSUE TITLE
User Reported Problem - GC report not showing correct data |arushi2stompmarket@gmail.com

### ISSUE THREAD

**Issue by testuser4stomp** [StompMarket/helpdesk#986]
Partner : OIR, User : arushi2stompmarket@gmail.com 
Problem : Data of sales report is incorrect. Not mapping returns.
Router Link : /catalog/brands/3

**Comment by anban4u** [comment]
@maheshstomp please work with aarushi to find out what exactly is incorrect. The information is insufficient.

Aarushi, please report to my office. I need to understand where is the gap. Need better explanation than this. Returns are not part of gc reports so I don't understand this.

**Comment by maheshstomp** [comment]
she wants return should also counted in GC report , discussed with her , for now track that manually . we can do this in future .
